"""Tests for checkowners.generate module."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from unittest.mock import patch

import pytest

from checkowners.generate import (
    CodeownersOverwriteError,
    _build_codeowners_content,
    _collect_unowned_paths,
    _consolidate,
    generate_codeowners,
)
from checkowners.models import (
    AnalysisConfig,
    Config,
    GithubConfig,
    OutputConfig,
    OwnerEntry,
    OwnershipMap,
    PathOwnership,
)

_NOW = datetime(2026, 5, 28, 12, 0, 0, tzinfo=UTC)


def _entry(handle: str, confidence: float, commits: int = 5) -> OwnerEntry:
    return OwnerEntry(
        handle=handle,
        confidence=confidence,
        last_commit=_NOW,
        commits=commits,
    )


def _make_ownership(
    raw: dict[str, tuple[OwnerEntry, ...]],
) -> OwnershipMap:
    paths = {p: PathOwnership(owners=owners, bus_factor=len(owners)) for p, owners in raw.items()}
    return OwnershipMap(paths=paths, last_analyzed=_NOW)


def _zero_threshold(**output_kwargs: object) -> Config:
    return Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        output=OutputConfig(**output_kwargs),  # type: ignore[arg-type]
    )


def test_generate_writes_file(tmp_path: Path) -> None:
    ownership = _make_ownership({"src/main.py": (_entry("alice@example.com", 0.9),)})
    config = _zero_threshold()
    content = generate_codeowners(tmp_path, ownership, config)
    codeowners = tmp_path / ".github" / "CODEOWNERS"
    assert codeowners.exists()
    assert codeowners.read_text(encoding="utf-8") == content


def test_generate_includes_header() -> None:
    ownership = _make_ownership({"src/main.py": (_entry("alice@example.com", 0.9),)})
    config = _zero_threshold()
    content = _build_codeowners_content(ownership, config)
    assert content.startswith("# Generated by checkOwners. Do not edit manually.")


def test_generate_refuses_to_overwrite_handwritten_file(tmp_path: Path) -> None:
    """A curated CODEOWNERS (no machine header) must never be clobbered."""
    target = tmp_path / ".github" / "CODEOWNERS"
    target.parent.mkdir(parents=True)
    target.write_text("# Hand-curated\nsrc/ @human\n", encoding="utf-8")
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    with pytest.raises(CodeownersOverwriteError):
        generate_codeowners(tmp_path, ownership, _zero_threshold())
    assert "@human" in target.read_text(encoding="utf-8")


def test_generate_force_overwrites_handwritten_file(tmp_path: Path) -> None:
    target = tmp_path / ".github" / "CODEOWNERS"
    target.parent.mkdir(parents=True)
    target.write_text("# Hand-curated\nsrc/ @human\n", encoding="utf-8")
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    generate_codeowners(tmp_path, ownership, _zero_threshold(), force=True)
    assert "@alice" in target.read_text(encoding="utf-8")


def test_generate_overwrites_own_output(tmp_path: Path) -> None:
    """Regenerating over a previously generated file needs no --force."""
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    generate_codeowners(tmp_path, ownership, _zero_threshold())
    generate_codeowners(tmp_path, ownership, _zero_threshold())


def test_consolidates_uniform_directory() -> None:
    """Files under one dir with the same owner set collapse to a dir rule."""
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@alice", 0.7),),
        }
    )
    config = _zero_threshold()
    content = _build_codeowners_content(ownership, config)
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/ @alice"]


def test_consolidation_covers_nested_dirs() -> None:
    ownership = _make_ownership(
        {
            "src/api/a.py": (_entry("@alice", 0.9),),
            "src/lib/b.py": (_entry("@alice", 0.7),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/ @alice"]


def test_mixed_directory_keeps_file_rules() -> None:
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@bob", 0.8),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/a.py @alice", "/src/b.py @bob"]


def test_partial_consolidation() -> None:
    """Uniform subtree consolidates even when a sibling subtree is mixed."""
    ownership = _make_ownership(
        {
            "docs/x.md": (_entry("@carol", 0.9),),
            "docs/y.md": (_entry("@carol", 0.8),),
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@bob", 0.8),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/docs/ @carol", "/src/a.py @alice", "/src/b.py @bob"]


def test_whole_repo_uniform_becomes_catch_all() -> None:
    ownership = _make_ownership(
        {
            "docs/x.md": (_entry("@alice", 0.9),),
            "src/a.py": (_entry("@alice", 0.8),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["* @alice"]


def test_consolidation_merges_owner_stats() -> None:
    """Dir-level owners aggregate confidence (mean) and commits (sum)."""
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9, commits=4),),
            "src/b.py": (_entry("@alice", 0.5, commits=6),),
        }
    )
    rows = _consolidate(
        [
            ("src/a.py", ownership.paths["src/a.py"].owners),
            ("src/b.py", ownership.paths["src/b.py"].owners),
        ]
    )
    assert len(rows) == 1
    merged = rows[0].owners[0]
    assert merged.confidence == pytest.approx(0.7)
    assert merged.commits == 10


def test_consolidation_disabled_keeps_per_file_lines() -> None:
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@alice", 0.7),),
        }
    )
    config = _zero_threshold(consolidate=False)
    content = _build_codeowners_content(ownership, config)
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/a.py @alice", "/src/b.py @alice"]


def test_single_file_dir_not_consolidated() -> None:
    ownership = _make_ownership({"src/a.py": (_entry("@alice", 0.9),)})
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/a.py @alice"]


def test_multiple_owners_ordered_by_confidence() -> None:
    ownership = _make_ownership(
        {"src/main.py": (_entry("@alice", 0.9), _entry("@bob", 0.6))},
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert "/src/main.py @alice @bob" in content


def test_confidence_threshold_filters_owners() -> None:
    config = Config(analysis=AnalysisConfig(confidence_threshold=0.5))
    ownership = _make_ownership(
        {"src/main.py": (_entry("@alice", 0.9), _entry("@bob", 0.2))},
    )
    content = _build_codeowners_content(ownership, config)
    assert "@bob" not in content
    assert "/src/main.py @alice" in content


def test_include_confidence_annotations() -> None:
    config = _zero_threshold(include_confidence=True)
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.92),)})
    content = _build_codeowners_content(ownership, config)
    assert "# @alice(0.92)" in content


def test_no_confidence_annotations_by_default() -> None:
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.92),)})
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert "(0.92)" not in content


def test_include_unowned_lists_paths() -> None:
    config = _zero_threshold(include_unowned=True)
    ownership = _make_ownership(
        {
            "src/main.py": (_entry("@alice", 0.9),),
            "orphan/lost.py": (),
        }
    )
    content = _build_codeowners_content(ownership, config)
    assert "# Unowned paths (needs triage)" in content
    assert "# /orphan/lost.py" in content


def test_collect_unowned_paths() -> None:
    ownership = _make_ownership({"a.py": (), "b.py": (_entry("@x", 0.9),)})
    assert _collect_unowned_paths(ownership) == ["/a.py"]


def test_team_resolution_collapses_owner_set(tmp_path: Path) -> None:
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        github=GithubConfig(org="acme", resolve_teams=True),
    )
    ownership = _make_ownership(
        {"src/main.py": (_entry("@alice", 0.9), _entry("@bob", 0.8))},
    )
    with patch(
        "checkowners.github.create_team_resolver",
        return_value=lambda owners: "@acme/backend",
    ):
        content = _build_codeowners_content(ownership, config, token="t", org="acme")
    assert "/src/main.py @acme/backend" in content


def test_output_ends_with_newline() -> None:
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert content.endswith("\n")
