"""Tests for checkowners.generate module."""

from __future__ import annotations

from contextlib import nullcontext
from datetime import UTC, datetime
from pathlib import Path
from unittest.mock import patch

import pytest

from checkowners.generate import (
    CodeownersOverwriteError,
    CodeownersSizeError,
    CodeownersVerificationError,
    _build_codeowners_content,
    _collect_unowned_paths,
    _consolidate,
    _render_codeowners,
    broad_pattern_warning,
    generate_codeowners,
    verify_round_trip,
)
from checkowners.models import (
    AnalysisConfig,
    Config,
    GithubConfig,
    OutputConfig,
    OwnerEntry,
    OwnershipMap,
    PathOwnership,
)
from checkowners.patterns import match_path, parse_rules, pattern_matches
from tests.conftest import (
    GitRepo,
    analyze_regression_repo,
    regression_analysis_config,
    script_regression_repo,
)

_NOW = datetime(2026, 5, 28, 12, 0, 0, tzinfo=UTC)


def _entry(handle: str, confidence: float, commits: int = 5) -> OwnerEntry:
    return OwnerEntry(
        handle=handle,
        ownership_score=confidence,
        last_commit=_NOW,
        commits=commits,
    )


def _make_ownership(
    raw: dict[str, tuple[OwnerEntry, ...]],
) -> OwnershipMap:
    paths = {
        p: PathOwnership(owners=owners, qualified_owner_count=len(owners))
        for p, owners in raw.items()
    }
    return OwnershipMap(paths=paths, last_analyzed=_NOW)


def _zero_threshold(
    *,
    include_unowned: bool = False,
    include_confidence: bool = False,
    consolidate: bool = True,
    allow_broad_patterns: bool = False,
) -> Config:
    return Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        output=OutputConfig(
            include_unowned=include_unowned,
            include_confidence=include_confidence,
            consolidate=consolidate,
            allow_broad_patterns=allow_broad_patterns,
        ),
    )


def test_generate_writes_file(tmp_path: Path) -> None:
    ownership = _make_ownership({"src/main.py": (_entry("alice@example.com", 0.9),)})
    config = _zero_threshold()
    result = generate_codeowners(tmp_path, ownership, config)
    codeowners = tmp_path / ".github" / "CODEOWNERS"
    assert codeowners.exists()
    assert codeowners.read_text(encoding="utf-8") == result.content


def test_generate_includes_header() -> None:
    ownership = _make_ownership({"src/main.py": (_entry("alice@example.com", 0.9),)})
    config = _zero_threshold()
    content = _build_codeowners_content(ownership, config)
    assert content.startswith("# Generated by checkOwners. Do not edit manually.")


def test_generate_refuses_to_overwrite_handwritten_file(tmp_path: Path) -> None:
    """A curated CODEOWNERS (no machine header) must never be clobbered."""
    target = tmp_path / ".github" / "CODEOWNERS"
    target.parent.mkdir(parents=True)
    target.write_text("# Hand-curated\nsrc/ @human\n", encoding="utf-8")
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    with pytest.raises(CodeownersOverwriteError):
        generate_codeowners(tmp_path, ownership, _zero_threshold())
    assert "@human" in target.read_text(encoding="utf-8")


def test_generate_force_overwrites_handwritten_file(tmp_path: Path) -> None:
    target = tmp_path / ".github" / "CODEOWNERS"
    target.parent.mkdir(parents=True)
    target.write_text("# Hand-curated\nsrc/ @human\n", encoding="utf-8")
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    generate_codeowners(tmp_path, ownership, _zero_threshold(), force=True)
    assert "@alice" in target.read_text(encoding="utf-8")


def test_generate_overwrites_own_output(tmp_path: Path) -> None:
    """Regenerating over a previously generated file needs no --force."""
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    generate_codeowners(tmp_path, ownership, _zero_threshold())
    generate_codeowners(tmp_path, ownership, _zero_threshold())


def test_consolidates_uniform_directory() -> None:
    """Files under one dir with the same owner set collapse to a dir rule."""
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@alice", 0.7),),
        }
    )
    config = _zero_threshold()
    content = _build_codeowners_content(ownership, config)
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/ @alice"]


def test_consolidation_covers_nested_dirs() -> None:
    ownership = _make_ownership(
        {
            "src/api/a.py": (_entry("@alice", 0.9),),
            "src/lib/b.py": (_entry("@alice", 0.7),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/ @alice"]


def test_mixed_directory_keeps_file_rules() -> None:
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@bob", 0.8),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/a.py @alice", "/src/b.py @bob"]


def test_partial_consolidation() -> None:
    """Uniform subtree consolidates even when a sibling subtree is mixed."""
    ownership = _make_ownership(
        {
            "docs/x.md": (_entry("@carol", 0.9),),
            "docs/y.md": (_entry("@carol", 0.8),),
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@bob", 0.8),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/docs/ @carol", "/src/a.py @alice", "/src/b.py @bob"]


def test_whole_repo_uniform_becomes_catch_all() -> None:
    ownership = _make_ownership(
        {
            "docs/x.md": (_entry("@alice", 0.9),),
            "src/a.py": (_entry("@alice", 0.8),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["* @alice"]


def test_consolidation_merges_owner_stats() -> None:
    """Dir-level owners aggregate confidence (mean) and commits (sum)."""
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9, commits=4),),
            "src/b.py": (_entry("@alice", 0.5, commits=6),),
        }
    )
    rows = _consolidate(
        [
            ("src/a.py", ownership.paths["src/a.py"].owners),
            ("src/b.py", ownership.paths["src/b.py"].owners),
        ]
    )
    assert len(rows) == 1
    merged = rows[0].owners[0]
    assert merged.confidence == pytest.approx(0.7)
    assert merged.commits == 10


def test_consolidation_disabled_keeps_per_file_lines() -> None:
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@alice", 0.7),),
        }
    )
    config = _zero_threshold(consolidate=False)
    content = _build_codeowners_content(ownership, config)
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/a.py @alice", "/src/b.py @alice"]


def test_single_file_dir_not_consolidated() -> None:
    ownership = _make_ownership({"src/a.py": (_entry("@alice", 0.9),)})
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/a.py @alice"]


def test_multiple_owners_ordered_by_confidence() -> None:
    ownership = _make_ownership(
        {"src/main.py": (_entry("@alice", 0.9), _entry("@bob", 0.6))},
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert "/src/main.py @alice @bob" in content


def test_confidence_threshold_filters_owners() -> None:
    config = Config(analysis=AnalysisConfig(confidence_threshold=0.5))
    ownership = _make_ownership(
        {"src/main.py": (_entry("@alice", 0.9), _entry("@bob", 0.2))},
    )
    content = _build_codeowners_content(ownership, config)
    assert "@bob" not in content
    assert "/src/main.py @alice" in content


def test_include_confidence_annotations() -> None:
    config = _zero_threshold(include_confidence=True)
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.92),)})
    content = _build_codeowners_content(ownership, config)
    assert "# @alice(0.92/1.00)" in content


def test_no_confidence_annotations_by_default() -> None:
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.92),)})
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert "(0.92)" not in content


def test_include_unowned_lists_paths() -> None:
    config = _zero_threshold(include_unowned=True)
    ownership = _make_ownership(
        {
            "src/main.py": (_entry("@alice", 0.9),),
            "orphan/lost.py": (),
        }
    )
    content = _build_codeowners_content(ownership, config)
    assert "# Unowned paths (needs triage)" in content
    assert "# /orphan/lost.py" in content


def test_collect_unowned_paths() -> None:
    ownership = _make_ownership({"a.py": (), "b.py": (_entry("@x", 0.9),)})
    assert _collect_unowned_paths(ownership) == ["/a.py"]


def test_team_resolution_collapses_owner_set() -> None:
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        github=GithubConfig(org="acme", resolve_teams=True),
    )
    ownership = _make_ownership(
        {"src/main.py": (_entry("@alice", 0.9), _entry("@bob", 0.8))},
    )
    with patch(
        "checkowners.generate.create_team_resolver",
        return_value=lambda _owners: "@acme/backend",
    ):
        content = _build_codeowners_content(ownership, config, token="t", org="acme")
    assert "/src/main.py @acme/backend" in content


def test_team_resolution_keeps_handles_when_no_team() -> None:
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        github=GithubConfig(org="acme", resolve_teams=True),
    )
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    with patch(
        "checkowners.generate.create_team_resolver",
        return_value=lambda _owners: None,
    ):
        content = _build_codeowners_content(ownership, config, token="t", org="acme")
    assert "/src/main.py @alice" in content


def test_output_ends_with_newline() -> None:
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert content.endswith("\n")


def test_bracket_segments_become_wildcards() -> None:
    """A sibling directory makes /app/*/ lossy, so per-file wildcards are used."""
    ownership = _make_ownership(
        {
            "app/[teamId]/page.tsx": (_entry("@alice", 0.9),),
            "app/[teamId]/layout.tsx": (_entry("@alice", 0.8),),
            "app/static/index.tsx": (_entry("@bob", 0.9),),
        }
    )
    content, _expected, records = _render_codeowners(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == [
        "/app/*/layout.tsx @alice",
        "/app/*/page.tsx @alice",
        "/app/static/index.tsx @bob",
    ]
    assert "[" not in content
    assert records
    assert all(not record.accepted for record in records)
    payload = records[0].as_json()
    assert payload["accepted"] is False
    assert payload["owner_delta"]["intended"]
    warning = broad_pattern_warning(records[0])
    assert "WARNING: GitHub CODEOWNERS cannot precisely represent:" in warning
    assert "Generated fallback:" in warning
    assert "This also matches:" in warning
    assert "Affected owners differ. Refusing automatic consolidation." in warning


def test_colliding_sanitized_patterns_merge_owners() -> None:
    ownership = _make_ownership(
        {
            "app/[teamId]/page.tsx": (_entry("@alice", 0.9),),
            "app/[userId]/view.tsx": (_entry("@bob", 0.6),),
        }
    )
    config = _zero_threshold(consolidate=False)
    content = _build_codeowners_content(ownership, config)
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/app/*/page.tsx @alice", "/app/*/view.tsx @bob"]


@pytest.mark.parametrize(
    ("second_owner", "allow_broad", "expected_lines", "accepted"),
    [
        (
            "@bob",
            False,
            [
                "/app/*/page.tsx @bob",
                "/app/[teamId]/page.tsx @alice",
                "/app/[userId]/page.tsx @bob",
            ],
            False,
        ),
        ("@alice", False, ["/app/*/page.tsx @alice"], True),
        ("@bob", True, ["/app/*/page.tsx @alice @bob"], True),
    ],
)
def test_identical_sanitized_patterns_merge_owner_sets(
    second_owner: str,
    allow_broad: bool,
    expected_lines: list[str],
    accepted: bool,
) -> None:
    ownership = _make_ownership(
        {
            "app/[teamId]/page.tsx": (_entry("@alice", 0.9),),
            "app/[userId]/page.tsx": (_entry(second_owner, 0.6),),
            "app/*/page.tsx": (_entry(second_owner, 0.6),),
        }
    )
    config = _zero_threshold(consolidate=False, allow_broad_patterns=allow_broad)
    content, _expected, records = _render_codeowners(ownership, config)
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == expected_lines
    assert records
    assert all(record.accepted is accepted for record in records)
    payload = records[0].as_json()
    assert payload["accepted"] is accepted
    assert payload["generated_fallback"] == "app/*/page.tsx"
    if accepted:
        return
    warning = broad_pattern_warning(records[0])
    assert "WARNING: GitHub CODEOWNERS cannot precisely represent: app/[teamId]/page.tsx" in warning
    assert "Generated fallback: app/*/page.tsx" in warning
    assert "app/[userId]/page.tsx" in warning
    assert "Affected owners differ. Refusing automatic consolidation." in warning


def test_pattern_spaces_escaped_on_write() -> None:
    ownership = _make_ownership({"docs/getting started.md": (_entry("@alice", 0.9),)})
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert "/docs/getting\\ started.md @alice" in content


_GOLDEN_CODEOWNERS = """\
# Generated by checkOwners. Do not edit manually.

/docs/ @carol
/src/a.py @alice
/src/b.py @bob
"""


def test_codeowners_output_is_byte_stable() -> None:
    ownership = _make_ownership(
        {
            "src/b.py": (_entry("@bob", 0.8),),
            "docs/y.md": (_entry("@carol", 0.8),),
            "src/a.py": (_entry("@alice", 0.9),),
            "docs/x.md": (_entry("@carol", 0.9),),
        }
    )
    first = _build_codeowners_content(ownership, _zero_threshold())
    second = _build_codeowners_content(ownership, _zero_threshold())
    assert first == second
    assert first == _GOLDEN_CODEOWNERS


def test_verify_round_trip_catches_later_broad_rule() -> None:
    expected = {
        "src/a.py": frozenset({"@alice"}),
        "src/b.py": frozenset({"@alice"}),
    }
    content = "/src/ @alice\n* @bob\n"
    with pytest.raises(CodeownersVerificationError) as exc_info:
        verify_round_trip(content, expected)
    msg = str(exc_info.value)
    assert "src/a.py" in msg
    assert "@alice" in msg
    assert "@bob" in msg
    assert "* @bob" in msg


def test_generate_refuses_over_max_bytes(tmp_path: Path) -> None:
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        output=OutputConfig(max_bytes=20),
    )
    with pytest.raises(CodeownersSizeError, match=r"output\.max_bytes"):
        generate_codeowners(tmp_path, ownership, config)
    assert not (tmp_path / ".github" / "CODEOWNERS").exists()


def test_generate_skips_round_trip_when_disabled(tmp_path: Path) -> None:
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        output=OutputConfig(verify_round_trip=False),
    )
    result = generate_codeowners(tmp_path, ownership, config)
    assert "@alice" in result.content


def test_generate_force_writes_over_max_bytes(tmp_path: Path) -> None:
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        output=OutputConfig(max_bytes=20),
    )
    result = generate_codeowners(tmp_path, ownership, config, force=True)
    written = tmp_path / ".github" / "CODEOWNERS"
    assert written.exists()
    assert written.read_text(encoding="utf-8") == result.content


@pytest.mark.parametrize(
    ("raw", "token", "org"),
    [
        (
            {
                "src/a.py": (_entry("@alice", 0.9),),
                "src/b.py": (_entry("@alice", 0.7),),
            },
            "",
            "",
        ),
        (
            {
                "src/a.py": (_entry("@alice", 0.9),),
                "src/b.py": (_entry("@bob", 0.8),),
            },
            "",
            "",
        ),
        (
            {
                "a.py": (_entry("@alice", 0.9),),
                "b.py": (_entry("@alice", 0.8),),
            },
            "",
            "",
        ),
        (
            {"src/main.py": (_entry("@alice", 0.9), _entry("@bob", 0.8))},
            "t",
            "acme",
        ),
        (
            {
                "app/[teamId]/page.tsx": (_entry("@alice", 0.9),),
                "app/[userId]/page.tsx": (_entry("@bob", 0.6),),
            },
            "",
            "",
        ),
        (
            {
                "app/[teamId]/page.tsx": (_entry("@alice", 0.9),),
                "app/[teamId]/layout.tsx": (_entry("@alice", 0.8),),
                "app/static/index.tsx": (_entry("@bob", 0.9),),
            },
            "",
            "",
        ),
    ],
)
def test_generated_file_round_trips_inference(
    tmp_path: Path,
    raw: dict[str, tuple[OwnerEntry, ...]],
    token: str,
    org: str,
) -> None:
    ownership = _make_ownership(raw)
    config = _zero_threshold()
    if org:
        config = Config(
            analysis=AnalysisConfig(confidence_threshold=0.0),
            github=GithubConfig(org=org, resolve_teams=True),
        )
    team_patch = (
        patch(
            "checkowners.generate.create_team_resolver",
            return_value=lambda _owners: "@acme/backend",
        )
        if org
        else nullcontext()
    )
    with team_patch:
        written = generate_codeowners(tmp_path, ownership, config, token=token, org=org)
        _rendered, expected, _records = _render_codeowners(ownership, config, token=token, org=org)
    assert written.content == _rendered
    rules = parse_rules(written.content)
    for path, intended in expected.items():
        rule = match_path(rules, path)
        resolved = frozenset(o.casefold() for o in rule.owners) if rule else frozenset()
        assert resolved == intended


@pytest.mark.integration
def test_generate_sanitizes_tracked_bracket_and_space_paths(git_repo: GitRepo) -> None:
    script_regression_repo(git_repo)
    ownership = analyze_regression_repo(git_repo)
    written = generate_codeowners(git_repo.path, ownership, regression_analysis_config())
    rule_lines = [
        line for line in written.content.splitlines() if line and not line.startswith("#")
    ]
    assert rule_lines
    assert all("[" not in line and "]" not in line for line in rule_lines)
    assert any("getting\\ started.md" in line for line in rule_lines)
    bracket = next(path for path in git_repo.ls_files() if "[" in path and "]" in path)
    winner = match_path(parse_rules(written.content), bracket)
    assert winner is not None
    assert "[" not in winner.pattern and "]" not in winner.pattern
    assert pattern_matches(winner.pattern, bracket)
