"""Tests for checkowners.config module."""

from __future__ import annotations

import re
import warnings
from pathlib import Path

import pytest
import yaml

from checkowners.config import find_codeowners_path, load_config
from checkowners.models import Config, DriftConfig, QualificationConfig, models_payload


def _write_config(tmp_path: Path, content: str) -> Path:
    config_dir = tmp_path / ".github"
    config_dir.mkdir(exist_ok=True)
    text = content
    first = text.lstrip().splitlines()[0] if text.strip() else ""
    if first and ":" in first and not first.startswith("version:"):
        text = f"version: 1\n{text}"
    (config_dir / "checkowners.yml").write_text(text, encoding="utf-8")
    return tmp_path


def test_load_config_defaults(tmp_path: Path) -> None:
    cfg = load_config(repo_root=tmp_path)
    assert cfg == Config()
    assert cfg.analysis.lookback_days == 365
    assert cfg.analysis.min_commits == 1
    assert cfg.qualification == QualificationConfig()
    assert cfg.qualification.strategy == "adaptive"
    assert cfg.qualification.min_commits == 1
    assert cfg.qualification.strong_blame_override == 0.5
    assert cfg.analysis.top_n_owners == 3
    assert cfg.analysis.confidence_threshold == 0.3
    assert cfg.paths.exclude == (
        "*.lock",
        "package-lock.json",
        "pnpm-lock.yaml",
        "dist/**",
        "vendor/**",
        "node_modules/**",
        "*.generated.*",
        "*.min.js",
        "*.min.css",
        "*.map",
        "*.whl",
        ".github/CODEOWNERS",
        "CODEOWNERS",
        "docs/CODEOWNERS",
    )
    assert cfg.output.header == "# Generated by checkOwners. Do not edit manually."
    assert cfg.output.include_unowned is False
    assert cfg.output.include_confidence is False
    assert cfg.output.consolidate is True
    assert cfg.output.max_bytes == 2_500_000
    assert cfg.output.verify_round_trip is True
    assert cfg.output.allow_broad_patterns is False
    assert cfg.drift.mode == "commit"
    assert cfg.drift.min_confidence_delta == 0.2
    assert cfg.drift.hysteresis_runs == 1
    assert cfg.drift.baseline_file == ""
    assert cfg.suppressions == ()
    assert cfg.scoring.recency_half_life_days == 90
    assert cfg.scoring.recency_weight == 0.35
    assert cfg.scoring.frequency_weight == 0.25
    assert cfg.scoring.blame_weight == 0.25
    assert cfg.scoring.review_weight == 0.15
    assert cfg.scoring.recency_reliability == 1.0
    assert cfg.scoring.frequency_reliability == 1.0
    assert cfg.scoring.blame_reliability == 1.0
    assert cfg.scoring.review_reliability == 1.0
    assert cfg.decay.threshold_days == 180
    assert cfg.decay.alert_on_decay is True
    assert cfg.bus_factor.critical_threshold == 1
    assert cfg.bus_factor.warn_threshold == 2
    assert cfg.git.blame_ignore_revs_file == ".git-blame-ignore-revs"
    assert cfg.git.detect_moves is True
    assert cfg.git.mass_refactor_file_fraction == 0.5
    assert cfg.git.use_mailmap is True


def test_drift_mode_default_matches_documented_surfaces() -> None:
    root = Path(__file__).resolve().parents[1]
    expected = DriftConfig().mode

    usage = (root / "docs" / "USAGE.md").read_text(encoding="utf-8")
    usage_match = re.search(r"(?m)^drift:\n  mode: (\w+)", usage)
    assert usage_match is not None
    assert usage_match.group(1) == expected

    action = (root / "action.yml").read_text(encoding="utf-8")
    action_match = re.search(r"(?m)^  mode:\n(?:    .*\n)*?    default: (\S+)", action)
    assert action_match is not None
    assert action_match.group(1) == expected


def test_load_config_empty_file(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "")
    cfg = load_config(repo_root=root)
    assert cfg == Config()


def test_load_config_partial_override(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "analysis:\n  lookback_days: 180\ngit:\n  detect_moves: true\n")
    cfg = load_config(repo_root=root)
    assert cfg.analysis.lookback_days == 180
    assert cfg.analysis.min_commits == 1
    assert cfg.qualification.min_commits == 1
    assert cfg.analysis.top_n_owners == 3
    assert cfg.paths == Config().paths
    assert cfg.output == Config().output
    assert cfg.git.use_mailmap is True


def test_load_config_full_override(tmp_path: Path) -> None:
    content = """\
analysis:
  lookback_days: 90
  min_commits: 5
  top_n_owners: 2
  confidence_threshold: 0.5
  respect_gitattributes: false
scoring:
  recency_half_life_days: 60
  recency_weight: 0.5
  frequency_weight: 0.2
  blame_weight: 0.2
  review_weight: 0.1
  recency_reliability: 0.9
  frequency_reliability: 0.8
  blame_reliability: 0.7
  review_reliability: 0.6
decay:
  threshold_days: 90
  alert_on_decay: false
bus_factor:
  critical_threshold: 2
  warn_threshold: 3
paths:
  exclude:
    - "*.tmp"
    - "build/**"
output:
  header: "# Custom header"
  include_unowned: true
  include_confidence: true
  max_bytes: 1000000
  verify_round_trip: false
  allow_broad_patterns: true
drift:
  mode: repo
  min_confidence_delta: 0.4
  hysteresis_runs: 3
github:
  org: myorg
  resolve_handles: false
  resolve_teams: false
  api_enabled: true
git:
  blame_ignore_revs_file: ignore-revs.txt
  detect_moves: false
  mass_refactor_file_fraction: 0.3
identity:
  mailmap: false
"""
    root = _write_config(tmp_path, content)
    cfg = load_config(repo_root=root)
    assert cfg.analysis.lookback_days == 90
    assert cfg.analysis.min_commits == 5
    assert cfg.qualification.min_commits == 5
    assert cfg.analysis.top_n_owners == 2
    assert cfg.analysis.confidence_threshold == 0.5
    assert cfg.analysis.respect_gitattributes is False
    assert cfg.scoring.recency_half_life_days == 60
    assert cfg.scoring.recency_weight == 0.5
    assert cfg.scoring.frequency_weight == 0.2
    assert cfg.scoring.blame_weight == 0.2
    assert cfg.scoring.review_weight == 0.1
    assert cfg.scoring.recency_reliability == 0.9
    assert cfg.scoring.frequency_reliability == 0.8
    assert cfg.scoring.blame_reliability == 0.7
    assert cfg.scoring.review_reliability == 0.6
    assert cfg.decay.threshold_days == 90
    assert cfg.decay.alert_on_decay is False
    assert cfg.bus_factor.critical_threshold == 2
    assert cfg.bus_factor.warn_threshold == 3
    assert cfg.paths.exclude == ("*.tmp", "build/**")
    assert cfg.output.header == "# Custom header"
    assert cfg.output.include_unowned is True
    assert cfg.output.include_confidence is True
    assert cfg.output.max_bytes == 1_000_000
    assert cfg.output.verify_round_trip is False
    assert cfg.output.allow_broad_patterns is True
    assert cfg.drift.mode == "repo"
    assert cfg.drift.min_confidence_delta == 0.4
    assert cfg.drift.hysteresis_runs == 3
    assert cfg.drift.baseline_file == ""
    assert cfg.suppressions == ()
    assert cfg.github.org == "myorg"
    assert cfg.github.resolve_handles is False
    assert cfg.github.resolve_teams is False
    assert cfg.github.api_enabled is True
    assert cfg.git.blame_ignore_revs_file == "ignore-revs.txt"
    assert cfg.git.detect_moves is False
    assert cfg.git.mass_refactor_file_fraction == 0.3
    assert cfg.git.use_mailmap is False


def test_load_config_invalid_yaml(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "[[[invalid yaml")
    with pytest.raises(yaml.YAMLError):
        load_config(repo_root=root)


def test_load_config_non_mapping(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "- a\n- b\n")
    with pytest.raises(ValueError, match="expected a YAML mapping"):
        load_config(repo_root=root)


def test_load_config_unknown_keys_rejected(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "custom_field: true\nanother: 42\n")
    with pytest.raises(ValueError, match="Unsupported checkowners config key"):
        load_config(repo_root=root)


def test_load_config_custom_repo_root(tmp_path: Path) -> None:
    sub = tmp_path / "myrepo"
    sub.mkdir()
    root = _write_config(sub, "analysis:\n  min_commits: 10\n")
    cfg = load_config(repo_root=root)
    assert cfg.analysis.min_commits == 10


def test_drift_mode_literal(tmp_path: Path) -> None:
    for mode in ("commit", "repo", "both"):
        root = _write_config(tmp_path, f"drift:\n  mode: {mode}\n")
        cfg = load_config(repo_root=root)
        assert cfg.drift.mode == mode
        (tmp_path / ".github" / "checkowners.yml").unlink()
        (tmp_path / ".github").rmdir()


def test_drift_mode_invalid_rejected(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "drift:\n  mode: nonsense\n")
    with pytest.raises(ValueError, match=r"Invalid drift\.mode"):
        load_config(repo_root=root)


def test_hysteresis_runs_invalid_rejected(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "drift:\n  hysteresis_runs: 0\n")
    with pytest.raises(ValueError, match=r"Invalid drift\.hysteresis_runs"):
        load_config(repo_root=root)


def test_drift_mode_env_override(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    root = _write_config(tmp_path, "drift:\n  mode: commit\n")
    monkeypatch.setenv("CHECKOWNERS_DRIFT_MODE", "both")
    cfg = load_config(repo_root=root)
    assert cfg.drift.mode == "both"


def test_drift_mode_env_override_without_config_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("CHECKOWNERS_DRIFT_MODE", "repo")
    cfg = load_config(repo_root=tmp_path)
    assert cfg.drift.mode == "repo"


def test_drift_mode_env_override_invalid_rejected(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("CHECKOWNERS_DRIFT_MODE", "sideways")
    with pytest.raises(ValueError, match="Invalid CHECKOWNERS_DRIFT_MODE"):
        load_config(repo_root=tmp_path)


def test_config_path_env_override_relative(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    (tmp_path / "custom.yml").write_text(
        "version: 1\nanalysis:\n  min_commits: 7\n", encoding="utf-8"
    )
    monkeypatch.setenv("CHECKOWNERS_CONFIG", "custom.yml")
    cfg = load_config(repo_root=tmp_path)
    assert cfg.analysis.min_commits == 7


def test_config_path_env_override_absolute(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    custom = tmp_path / "elsewhere" / "co.yml"
    custom.parent.mkdir()
    custom.write_text("version: 1\nanalysis:\n  top_n_owners: 9\n", encoding="utf-8")
    monkeypatch.setenv("CHECKOWNERS_CONFIG", str(custom))
    # repo_root deliberately points somewhere without a config file.
    cfg = load_config(repo_root=tmp_path)
    assert cfg.analysis.top_n_owners == 9


def test_paths_exclude_override(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "paths:\n  exclude:\n    - '*.tmp'\n")
    cfg = load_config(repo_root=root)
    assert cfg.paths.exclude == ("*.tmp",)
    assert "*.lock" not in cfg.paths.exclude


def test_load_config_github_section(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "github:\n  org: myorg\n  resolve_teams: false\n")
    cfg = load_config(repo_root=root)
    assert cfg.github.org == "myorg"
    assert cfg.github.resolve_teams is False
    assert cfg.github.resolve_handles is True
    assert cfg.github.api_enabled is False


def test_load_config_github_token_rejected(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "github:\n  token: ghp_secret\n")
    with pytest.raises(ValueError, match=r"github\.token is not accepted"):
        load_config(repo_root=root)


def test_load_config_scoring_section(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "scoring:\n  recency_weight: 0.5\n")
    cfg = load_config(repo_root=root)
    assert cfg.scoring.recency_weight == 0.5
    assert cfg.scoring.frequency_weight == 0.25


def test_load_config_qualification_section(tmp_path: Path) -> None:
    root = _write_config(
        tmp_path,
        "qualification:\n  strategy: threshold\n  min_commits: 3\n  strong_blame_override: 0.7\n",
    )
    cfg = load_config(repo_root=root)
    assert cfg.qualification.strategy == "threshold"
    assert cfg.qualification.min_commits == 3
    assert cfg.qualification.strong_blame_override == 0.7
    assert cfg.analysis.min_commits == 3


def test_qualification_min_commits_wins_over_analysis(tmp_path: Path) -> None:
    root = _write_config(
        tmp_path,
        "analysis:\n  min_commits: 5\nqualification:\n  min_commits: 2\n",
    )
    cfg = load_config(repo_root=root)
    assert cfg.analysis.min_commits == 2
    assert cfg.qualification.min_commits == 2


def test_qualification_strategy_invalid_rejected(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "qualification:\n  strategy: fuzzy\n")
    with pytest.raises(ValueError, match=r"Invalid qualification\.strategy"):
        load_config(repo_root=root)


def test_git_mass_refactor_fraction_invalid_rejected(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "git:\n  mass_refactor_file_fraction: 1.5\n")
    with pytest.raises(ValueError, match=r"Invalid git\.mass_refactor_file_fraction"):
        load_config(repo_root=root)


def test_find_codeowners_path_github_dir(tmp_path: Path) -> None:
    (tmp_path / ".github").mkdir()
    (tmp_path / ".github" / "CODEOWNERS").write_text("# test", encoding="utf-8")
    assert find_codeowners_path(tmp_path) == tmp_path / ".github" / "CODEOWNERS"


def test_find_codeowners_path_root(tmp_path: Path) -> None:
    (tmp_path / "CODEOWNERS").write_text("# test", encoding="utf-8")
    assert find_codeowners_path(tmp_path) == tmp_path / "CODEOWNERS"


def test_find_codeowners_path_docs(tmp_path: Path) -> None:
    (tmp_path / "docs").mkdir()
    (tmp_path / "docs" / "CODEOWNERS").write_text("# test", encoding="utf-8")
    assert find_codeowners_path(tmp_path) == tmp_path / "docs" / "CODEOWNERS"


def test_find_codeowners_path_priority(tmp_path: Path) -> None:
    (tmp_path / ".github").mkdir()
    (tmp_path / ".github" / "CODEOWNERS").write_text("# github", encoding="utf-8")
    (tmp_path / "CODEOWNERS").write_text("# root", encoding="utf-8")
    assert find_codeowners_path(tmp_path) == tmp_path / ".github" / "CODEOWNERS"


def test_find_codeowners_path_none_exist(tmp_path: Path) -> None:
    assert find_codeowners_path(tmp_path) == tmp_path / ".github" / "CODEOWNERS"


_V1_MOVED = """\
analysis:
  top_n_owners: 4
  min_commits: 2
  exclude_bots: false
scoring:
  recency_weight: 0.4
  frequency_weight: 0.2
  blame_weight: 0.2
  review_weight: 0.2
  recency_half_life_days: 30
  recency_reliability: 0.9
  frequency_reliability: 0.8
  blame_reliability: 0.7
  review_reliability: 0.6
"""


def _v2_alias() -> str:
    models = models_payload()
    return f"""\
version: 1
analysis:
  max_owners: 4
qualification:
  min_commits: 2
bots:
  exclude: false
model:
  ownership: {models["ownership"]}
  risk: {models["risk"]}
  topology: {models["topology"]}
  signals:
    recency:
      weight: 0.4
      half_life_days: 30
      reliability: 0.9
    frequency:
      weight: 0.2
      reliability: 0.8
    blame:
      weight: 0.2
      reliability: 0.7
    reviews:
      weight: 0.2
      reliability: 0.6
"""


def test_current_layout_loads(tmp_path: Path) -> None:
    flat = tmp_path / "flat"
    nested = tmp_path / "nested"
    flat.mkdir()
    nested.mkdir()
    _write_config(flat, _V1_MOVED)
    _write_config(nested, _v2_alias())
    loaded_flat = load_config(repo_root=flat)
    loaded_nested = load_config(repo_root=nested)
    assert loaded_flat == loaded_nested
    assert loaded_flat.analysis.top_n_owners == 4
    assert loaded_flat.analysis.exclude_bots is False
    assert loaded_flat.qualification.min_commits == 2
    assert loaded_flat.scoring.recency_half_life_days == 30
    assert loaded_flat.scoring.review_weight == 0.2
    assert loaded_flat.scoring.blame_reliability == 0.7


def test_missing_or_old_config_version_rejected(tmp_path: Path) -> None:
    missing = tmp_path / "missing"
    missing.mkdir()
    _write_config(missing, "analysis:\n  lookback_days: 10\n")
    (missing / ".github" / "checkowners.yml").write_text(
        "analysis:\n  lookback_days: 10\n",
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="requires version: 1"):
        load_config(repo_root=missing)
    old = tmp_path / "old"
    old.mkdir()
    _write_config(old, "version: 2\n")
    with pytest.raises(ValueError, match="Unsupported checkowners config version"):
        load_config(repo_root=old)


def test_missing_config_does_not_warn(tmp_path: Path) -> None:
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        cfg = load_config(repo_root=tmp_path)
    assert cfg == Config()
    assert caught == []


def test_model_pin_must_match_implementation(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "version: 1\nmodel:\n  ownership: ownership-v2\n")
    with pytest.raises(ValueError, match=r"model\.ownership"):
        load_config(repo_root=root)


@pytest.mark.parametrize(
    ("content", "match"),
    [
        ("version: 3\n", "Unsupported checkowners config version"),
        ("version: '2'\n", "Unsupported checkowners config version"),
        ("version: 1\ncriticality:\n  'docs/**': 0.1\n", "criticality"),
        ("version: 1\nanalysis:\n  lookback_days: adaptive\n", "lookback_days"),
        (
            "version: 1\nmodel:\n  signals:\n    historical_depth:\n      weight: 0.1\n",
            "historical_depth",
        ),
    ],
)
def test_unknown_config_version_and_keys_rejected(tmp_path: Path, content: str, match: str) -> None:
    root = _write_config(tmp_path, content)
    with pytest.raises(ValueError, match=match):
        load_config(repo_root=root)


@pytest.mark.parametrize(
    ("content", "match"),
    [
        ("version: 1\nanalysis: []\n", "analysis must be a mapping"),
        ("version: 1\nsuppressions: {}\n", "suppressions must be a list"),
        ("version: 1\nanalysis:\n  max_owners: '4'\n", "analysis.max_owners must be an integer"),
        (
            "version: 1\nanalysis:\n  max_owners: 4\n  top_n_owners: 3\n",
            "disagree",
        ),
        ("version: 1\nbots:\n  exclude: 1\n", "bots.exclude must be a boolean"),
        (
            "version: 1\nanalysis:\n  exclude_bots: true\nbots:\n  exclude: false\n",
            "bots.exclude and analysis.exclude_bots disagree",
        ),
        (
            "version: 1\nscoring:\n  review_weight: 0.2\n"
            "model:\n  signals:\n    reviews:\n      weight: 0.3\n",
            "scoring.review_weight disagree",
        ),
    ],
)
def test_v2_invalid_aliases_rejected(tmp_path: Path, content: str, match: str) -> None:
    root = _write_config(tmp_path, content)
    with pytest.raises(ValueError, match=match):
        load_config(repo_root=root)


def test_v2_without_model_keeps_defaults(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "version: 1\n")
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        cfg = load_config(repo_root=root)
    assert caught == []
    assert cfg == Config()


def test_v2_alias_edges_load(tmp_path: Path) -> None:
    agreed = """\
version: 1
analysis:
  max_owners: 4
  top_n_owners: 4
  exclude_bots: false
bots:
  exclude: false
scoring:
  review_weight: 0.2
model:
  signals:
    reviews:
      weight: 0.2
suppressions:
  - path: legacy/**
    rule: stale
    reason: later
"""
    omitted = """\
version: 1
analysis:
  lookback_days: 30
bots: {}
"""
    agreed_dir = tmp_path / "agreed"
    omitted_dir = tmp_path / "omitted"
    agreed_dir.mkdir()
    omitted_dir.mkdir()
    agreed_root = _write_config(agreed_dir, agreed)
    omitted_root = _write_config(omitted_dir, omitted)
    agreed_cfg = load_config(repo_root=agreed_root)
    omitted_cfg = load_config(repo_root=omitted_root)
    assert agreed_cfg.analysis.top_n_owners == 4
    assert agreed_cfg.analysis.exclude_bots is False
    assert agreed_cfg.scoring.review_weight == 0.2
    assert agreed_cfg.suppressions[0].path == "legacy/**"
    assert agreed_cfg.suppressions[0].rule == "stale"
    assert omitted_cfg.analysis.lookback_days == 30
    assert omitted_cfg.analysis.top_n_owners == 3
    assert omitted_cfg.analysis.exclude_bots is True


def test_analysis_budgets_and_incomplete_policy(tmp_path: Path) -> None:
    root = _write_config(
        tmp_path,
        "version: 1\n"
        "analysis:\n"
        "  max_runtime_seconds: 10\n"
        "  max_git_workers: 2\n"
        "  max_api_requests: 5\n"
        "policy:\n"
        "  incomplete_analysis:\n"
        "    fail: true\n",
    )
    cfg = load_config(repo_root=root)
    assert cfg.analysis.max_runtime_seconds == 10
    assert cfg.analysis.max_git_workers == 2
    assert cfg.analysis.max_api_requests == 5
    assert cfg.policy.incomplete_analysis_fail is True


def test_policy_without_a_fail_flag_stays_off(tmp_path: Path) -> None:
    empty = tmp_path / "empty"
    omitted = tmp_path / "omitted"
    blank = tmp_path / "blank"
    empty.mkdir()
    omitted.mkdir()
    blank.mkdir()
    _write_config(empty, "version: 1\npolicy: {}\n")
    _write_config(omitted, "version: 1\npolicy:\n  incomplete_analysis: {}\n")
    _write_config(blank, "version: 1\npolicy:\n  incomplete_analysis: []\n")
    assert load_config(repo_root=empty).policy.incomplete_analysis_fail is False
    assert load_config(repo_root=omitted).policy.incomplete_analysis_fail is False
    with pytest.raises(ValueError, match="must be a mapping"):
        load_config(repo_root=blank)


def test_policy_fail_rejects_non_booleans(tmp_path: Path) -> None:
    current = tmp_path / "current"
    legacy = tmp_path / "legacy"
    current.mkdir()
    legacy.mkdir()
    _write_config(current, "version: 1\npolicy:\n  incomplete_analysis:\n    fail: 1\n")
    _write_config(legacy, "policy:\n  incomplete_analysis:\n    fail: 1\n")
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", DeprecationWarning)
        with pytest.raises(ValueError, match="must be a boolean"):
            load_config(repo_root=current)
        with pytest.raises(ValueError, match="must be a boolean"):
            load_config(repo_root=legacy)


@pytest.mark.parametrize(
    ("content", "match"),
    [
        ("version: 1\nanalysis:\n  max_runtime_seconds: 0\n", "positive integer"),
        ("version: 1\nanalysis:\n  max_git_workers: -1\n", "positive integer"),
        ("version: 1\nanalysis:\n  max_api_requests: false\n", "positive integer"),
        ("version: 1\npolicy:\n  drift: {}\n", "Unsupported checkowners config key: policy.drift"),
    ],
)
def test_budget_and_policy_keys_rejected(tmp_path: Path, content: str, match: str) -> None:
    root = _write_config(tmp_path, content)
    with pytest.raises(ValueError, match=match):
        load_config(repo_root=root)
