"""Tests for checkowners.config module."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from checkowners.config import find_codeowners_path, load_config
from checkowners.models import Config


def _write_config(tmp_path: Path, content: str) -> Path:
    config_dir = tmp_path / ".github"
    config_dir.mkdir(exist_ok=True)
    (config_dir / "checkowners.yml").write_text(content, encoding="utf-8")
    return tmp_path


def test_load_config_defaults(tmp_path: Path) -> None:
    cfg = load_config(repo_root=tmp_path)
    assert cfg == Config()
    assert cfg.analysis.lookback_days == 365
    assert cfg.analysis.min_commits == 3
    assert cfg.analysis.top_n_owners == 3
    assert cfg.analysis.confidence_threshold == 0.3
    assert cfg.paths.exclude == (
        "*.lock",
        "package-lock.json",
        "pnpm-lock.yaml",
        "dist/**",
        "vendor/**",
        "node_modules/**",
        "*.generated.*",
        "*.min.js",
        "*.min.css",
        "*.map",
        "*.whl",
        ".github/CODEOWNERS",
        "CODEOWNERS",
        "docs/CODEOWNERS",
    )
    assert cfg.output.header == "# Generated by checkOwners. Do not edit manually."
    assert cfg.output.include_unowned is False
    assert cfg.output.include_confidence is False
    assert cfg.output.consolidate is True
    assert cfg.drift.mode == "commit"
    assert cfg.drift.min_confidence_delta == 0.2
    assert cfg.notifications.webhook_url == ""
    assert cfg.notifications.include_unchanged is False
    assert cfg.notifications.severity_threshold == "medium"
    assert cfg.scoring.recency_half_life_days == 90
    assert cfg.scoring.recency_weight == 0.35
    assert cfg.scoring.frequency_weight == 0.25
    assert cfg.scoring.blame_weight == 0.25
    assert cfg.scoring.review_weight == 0.15
    assert cfg.decay.threshold_days == 180
    assert cfg.decay.alert_on_decay is True
    assert cfg.bus_factor.critical_threshold == 1
    assert cfg.bus_factor.warn_threshold == 2


def test_load_config_empty_file(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "")
    cfg = load_config(repo_root=root)
    assert cfg == Config()


def test_load_config_partial_override(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "analysis:\n  lookback_days: 180\n")
    cfg = load_config(repo_root=root)
    assert cfg.analysis.lookback_days == 180
    assert cfg.analysis.min_commits == 3
    assert cfg.analysis.top_n_owners == 3
    assert cfg.paths == Config().paths
    assert cfg.output == Config().output


def test_load_config_full_override(tmp_path: Path) -> None:
    content = """\
analysis:
  lookback_days: 90
  min_commits: 5
  top_n_owners: 2
  confidence_threshold: 0.5
scoring:
  recency_half_life_days: 60
  recency_weight: 0.5
  frequency_weight: 0.2
  blame_weight: 0.2
  review_weight: 0.1
decay:
  threshold_days: 90
  alert_on_decay: false
bus_factor:
  critical_threshold: 2
  warn_threshold: 3
paths:
  exclude:
    - "*.tmp"
    - "build/**"
output:
  header: "# Custom header"
  include_unowned: true
  include_confidence: true
drift:
  mode: repo
  min_confidence_delta: 0.4
notifications:
  webhook_url: "https://hooks.example.com/drift"
  include_unchanged: true
  severity_threshold: high
github:
  org: myorg
  resolve_handles: false
  resolve_teams: false
  api_enabled: true
"""
    root = _write_config(tmp_path, content)
    cfg = load_config(repo_root=root)
    assert cfg.analysis.lookback_days == 90
    assert cfg.analysis.min_commits == 5
    assert cfg.analysis.top_n_owners == 2
    assert cfg.analysis.confidence_threshold == 0.5
    assert cfg.scoring.recency_half_life_days == 60
    assert cfg.scoring.recency_weight == 0.5
    assert cfg.scoring.frequency_weight == 0.2
    assert cfg.scoring.blame_weight == 0.2
    assert cfg.scoring.review_weight == 0.1
    assert cfg.decay.threshold_days == 90
    assert cfg.decay.alert_on_decay is False
    assert cfg.bus_factor.critical_threshold == 2
    assert cfg.bus_factor.warn_threshold == 3
    assert cfg.paths.exclude == ("*.tmp", "build/**")
    assert cfg.output.header == "# Custom header"
    assert cfg.output.include_unowned is True
    assert cfg.output.include_confidence is True
    assert cfg.drift.mode == "repo"
    assert cfg.drift.min_confidence_delta == 0.4
    assert cfg.notifications.webhook_url == "https://hooks.example.com/drift"
    assert cfg.notifications.include_unchanged is True
    assert cfg.notifications.severity_threshold == "high"
    assert cfg.github.org == "myorg"
    assert cfg.github.resolve_handles is False
    assert cfg.github.resolve_teams is False
    assert cfg.github.api_enabled is True


def test_load_config_invalid_yaml(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "[[[invalid yaml")
    with pytest.raises(yaml.YAMLError):
        load_config(repo_root=root)


def test_load_config_non_mapping(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "- a\n- b\n")
    with pytest.raises(ValueError, match="expected a YAML mapping"):
        load_config(repo_root=root)


def test_load_config_unknown_keys_ignored(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "custom_field: true\nanother: 42\n")
    cfg = load_config(repo_root=root)
    assert cfg == Config()


def test_load_config_custom_repo_root(tmp_path: Path) -> None:
    sub = tmp_path / "myrepo"
    sub.mkdir()
    root = _write_config(sub, "analysis:\n  min_commits: 10\n")
    cfg = load_config(repo_root=root)
    assert cfg.analysis.min_commits == 10


def test_drift_mode_literal(tmp_path: Path) -> None:
    for mode in ("commit", "repo", "both"):
        root = _write_config(tmp_path, f"drift:\n  mode: {mode}\n")
        cfg = load_config(repo_root=root)
        assert cfg.drift.mode == mode
        (tmp_path / ".github" / "checkowners.yml").unlink()
        (tmp_path / ".github").rmdir()


def test_drift_mode_invalid_rejected(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "drift:\n  mode: nonsense\n")
    with pytest.raises(ValueError, match="Invalid drift.mode"):
        load_config(repo_root=root)


def test_drift_mode_env_override(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    root = _write_config(tmp_path, "drift:\n  mode: commit\n")
    monkeypatch.setenv("CHECKOWNERS_DRIFT_MODE", "both")
    cfg = load_config(repo_root=root)
    assert cfg.drift.mode == "both"


def test_drift_mode_env_override_without_config_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("CHECKOWNERS_DRIFT_MODE", "repo")
    cfg = load_config(repo_root=tmp_path)
    assert cfg.drift.mode == "repo"


def test_drift_mode_env_override_invalid_rejected(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("CHECKOWNERS_DRIFT_MODE", "sideways")
    with pytest.raises(ValueError, match="Invalid CHECKOWNERS_DRIFT_MODE"):
        load_config(repo_root=tmp_path)


def test_config_path_env_override_relative(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    (tmp_path / "custom.yml").write_text("analysis:\n  min_commits: 7\n", encoding="utf-8")
    monkeypatch.setenv("CHECKOWNERS_CONFIG", "custom.yml")
    cfg = load_config(repo_root=tmp_path)
    assert cfg.analysis.min_commits == 7


def test_config_path_env_override_absolute(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    custom = tmp_path / "elsewhere" / "co.yml"
    custom.parent.mkdir()
    custom.write_text("analysis:\n  top_n_owners: 9\n", encoding="utf-8")
    monkeypatch.setenv("CHECKOWNERS_CONFIG", str(custom))
    # repo_root deliberately points somewhere without a config file.
    cfg = load_config(repo_root=tmp_path)
    assert cfg.analysis.top_n_owners == 9


def test_webhook_url_env_interpolation(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("CHECKOWNERS_WEBHOOK_URL", "https://hooks.example.com/secret")
    root = _write_config(tmp_path, "notifications:\n  webhook_url: ${CHECKOWNERS_WEBHOOK_URL}\n")
    cfg = load_config(repo_root=root)
    assert cfg.notifications.webhook_url == "https://hooks.example.com/secret"


def test_webhook_url_env_missing_resolves_empty(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "notifications:\n  webhook_url: ${UNSET_WEBHOOK}\n")
    cfg = load_config(repo_root=root)
    assert cfg.notifications.webhook_url == ""


def test_webhook_url_literal_passthrough(tmp_path: Path) -> None:
    root = _write_config(
        tmp_path, "notifications:\n  webhook_url: https://hooks.example.com/plain\n"
    )
    cfg = load_config(repo_root=root)
    assert cfg.notifications.webhook_url == "https://hooks.example.com/plain"


def test_severity_threshold_invalid_rejected(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "notifications:\n  severity_threshold: extreme\n")
    with pytest.raises(ValueError, match="Invalid notifications.severity_threshold"):
        load_config(repo_root=root)


def test_paths_exclude_override(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "paths:\n  exclude:\n    - '*.tmp'\n")
    cfg = load_config(repo_root=root)
    assert cfg.paths.exclude == ("*.tmp",)
    assert "*.lock" not in cfg.paths.exclude


def test_load_config_github_section(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "github:\n  org: myorg\n  resolve_teams: false\n")
    cfg = load_config(repo_root=root)
    assert cfg.github.org == "myorg"
    assert cfg.github.resolve_teams is False
    assert cfg.github.resolve_handles is True
    assert cfg.github.api_enabled is False


def test_load_config_github_token_rejected(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "github:\n  token: ghp_secret\n")
    with pytest.raises(ValueError, match="github.token is not accepted"):
        load_config(repo_root=root)


def test_load_config_scoring_section(tmp_path: Path) -> None:
    root = _write_config(tmp_path, "scoring:\n  recency_weight: 0.5\n")
    cfg = load_config(repo_root=root)
    assert cfg.scoring.recency_weight == 0.5
    assert cfg.scoring.frequency_weight == 0.25


def test_find_codeowners_path_github_dir(tmp_path: Path) -> None:
    (tmp_path / ".github").mkdir()
    (tmp_path / ".github" / "CODEOWNERS").write_text("# test", encoding="utf-8")
    assert find_codeowners_path(tmp_path) == tmp_path / ".github" / "CODEOWNERS"


def test_find_codeowners_path_root(tmp_path: Path) -> None:
    (tmp_path / "CODEOWNERS").write_text("# test", encoding="utf-8")
    assert find_codeowners_path(tmp_path) == tmp_path / "CODEOWNERS"


def test_find_codeowners_path_docs(tmp_path: Path) -> None:
    (tmp_path / "docs").mkdir()
    (tmp_path / "docs" / "CODEOWNERS").write_text("# test", encoding="utf-8")
    assert find_codeowners_path(tmp_path) == tmp_path / "docs" / "CODEOWNERS"


def test_find_codeowners_path_priority(tmp_path: Path) -> None:
    (tmp_path / ".github").mkdir()
    (tmp_path / ".github" / "CODEOWNERS").write_text("# github", encoding="utf-8")
    (tmp_path / "CODEOWNERS").write_text("# root", encoding="utf-8")
    assert find_codeowners_path(tmp_path) == tmp_path / ".github" / "CODEOWNERS"


def test_find_codeowners_path_none_exist(tmp_path: Path) -> None:
    assert find_codeowners_path(tmp_path) == tmp_path / ".github" / "CODEOWNERS"
