"""Tests for checkowners.generate module."""

from __future__ import annotations

import subprocess
from dataclasses import replace
from datetime import UTC, datetime
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from checkowners.generate import (
    CodeownersGenerationError,
    CodeownersOverwriteError,
    _build_codeowners_content,
    _collect_unowned_paths,
    _consolidate,
    _tracked_paths,
    generate_codeowners,
    verify_round_trip,
)
from checkowners.models import (
    AnalysisConfig,
    Config,
    GithubConfig,
    OutputConfig,
    OwnerEntry,
    OwnershipMap,
    PathOwnership,
)

_NOW = datetime(2026, 5, 28, 12, 0, 0, tzinfo=UTC)


def _entry(handle: str, confidence: float, commits: int = 5) -> OwnerEntry:
    return OwnerEntry(
        handle=handle,
        confidence=confidence,
        last_commit=_NOW,
        commits=commits,
    )


def _make_ownership(
    raw: dict[str, tuple[OwnerEntry, ...]],
) -> OwnershipMap:
    paths = {p: PathOwnership(owners=owners, bus_factor=len(owners)) for p, owners in raw.items()}
    return OwnershipMap(paths=paths, last_analyzed=_NOW)


def _zero_threshold(
    *,
    include_unowned: bool = False,
    include_confidence: bool = False,
    consolidate: bool = True,
) -> Config:
    return Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        output=OutputConfig(
            include_unowned=include_unowned,
            include_confidence=include_confidence,
            consolidate=consolidate,
        ),
    )


def test_generate_writes_file(tmp_path: Path) -> None:
    ownership = _make_ownership({"src/main.py": (_entry("alice@example.com", 0.9),)})
    config = _zero_threshold()
    content = generate_codeowners(tmp_path, ownership, config)
    codeowners = tmp_path / ".github" / "CODEOWNERS"
    assert codeowners.exists()
    assert codeowners.read_text(encoding="utf-8") == content


def test_generate_includes_header() -> None:
    ownership = _make_ownership({"src/main.py": (_entry("alice@example.com", 0.9),)})
    config = _zero_threshold()
    content = _build_codeowners_content(ownership, config)
    assert content.startswith("# Generated by checkOwners. Do not edit manually.")


def test_generate_refuses_to_overwrite_handwritten_file(tmp_path: Path) -> None:
    """A curated CODEOWNERS (no machine header) must never be clobbered."""
    target = tmp_path / ".github" / "CODEOWNERS"
    target.parent.mkdir(parents=True)
    target.write_text("# Hand-curated\nsrc/ @human\n", encoding="utf-8")
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    with pytest.raises(CodeownersOverwriteError):
        generate_codeowners(tmp_path, ownership, _zero_threshold())
    assert "@human" in target.read_text(encoding="utf-8")


def test_generate_force_overwrites_handwritten_file(tmp_path: Path) -> None:
    target = tmp_path / ".github" / "CODEOWNERS"
    target.parent.mkdir(parents=True)
    target.write_text("# Hand-curated\nsrc/ @human\n", encoding="utf-8")
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    generate_codeowners(tmp_path, ownership, _zero_threshold(), force=True)
    assert "@alice" in target.read_text(encoding="utf-8")


def test_generate_overwrites_own_output(tmp_path: Path) -> None:
    """Regenerating over a previously generated file needs no --force."""
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    generate_codeowners(tmp_path, ownership, _zero_threshold())
    generate_codeowners(tmp_path, ownership, _zero_threshold())


def test_consolidates_uniform_directory() -> None:
    """Files under one dir with the same owner set collapse to a dir rule."""
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@alice", 0.7),),
        }
    )
    config = _zero_threshold()
    content = _build_codeowners_content(ownership, config)
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/ @alice"]


def test_consolidation_covers_nested_dirs() -> None:
    ownership = _make_ownership(
        {
            "src/api/a.py": (_entry("@alice", 0.9),),
            "src/lib/b.py": (_entry("@alice", 0.7),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/ @alice"]


def test_mixed_directory_keeps_file_rules() -> None:
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@bob", 0.8),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/a.py @alice", "/src/b.py @bob"]


def test_partial_consolidation() -> None:
    """Uniform subtree consolidates even when a sibling subtree is mixed."""
    ownership = _make_ownership(
        {
            "docs/x.md": (_entry("@carol", 0.9),),
            "docs/y.md": (_entry("@carol", 0.8),),
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@bob", 0.8),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/docs/ @carol", "/src/a.py @alice", "/src/b.py @bob"]


def test_whole_repo_uniform_becomes_catch_all() -> None:
    ownership = _make_ownership(
        {
            "docs/x.md": (_entry("@alice", 0.9),),
            "src/a.py": (_entry("@alice", 0.8),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["* @alice"]


def test_consolidation_merges_owner_stats() -> None:
    """Dir-level owners aggregate confidence (mean) and commits (sum)."""
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9, commits=4),),
            "src/b.py": (_entry("@alice", 0.5, commits=6),),
        }
    )
    rows = _consolidate(
        [
            ("src/a.py", ownership.paths["src/a.py"].owners),
            ("src/b.py", ownership.paths["src/b.py"].owners),
        ]
    )
    assert len(rows) == 1
    merged = rows[0].owners[0]
    assert merged.confidence == pytest.approx(0.7)
    assert merged.commits == 10


def test_consolidation_disabled_keeps_per_file_lines() -> None:
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@alice", 0.7),),
        }
    )
    config = _zero_threshold(consolidate=False)
    content = _build_codeowners_content(ownership, config)
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/a.py @alice", "/src/b.py @alice"]


def test_single_file_dir_not_consolidated() -> None:
    ownership = _make_ownership({"src/a.py": (_entry("@alice", 0.9),)})
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/src/a.py @alice"]


def test_multiple_owners_ordered_by_confidence() -> None:
    ownership = _make_ownership(
        {"src/main.py": (_entry("@alice", 0.9), _entry("@bob", 0.6))},
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert "/src/main.py @alice @bob" in content


def test_confidence_threshold_filters_owners() -> None:
    config = Config(analysis=AnalysisConfig(confidence_threshold=0.5))
    ownership = _make_ownership(
        {"src/main.py": (_entry("@alice", 0.9), _entry("@bob", 0.2))},
    )
    content = _build_codeowners_content(ownership, config)
    assert "@bob" not in content
    assert "/src/main.py @alice" in content


def test_include_confidence_annotations() -> None:
    config = _zero_threshold(include_confidence=True)
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.92),)})
    content = _build_codeowners_content(ownership, config)
    assert "# @alice(0.92)" in content


def test_no_confidence_annotations_by_default() -> None:
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.92),)})
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert "(0.92)" not in content


def test_include_unowned_lists_paths() -> None:
    config = _zero_threshold(include_unowned=True)
    ownership = _make_ownership(
        {
            "src/main.py": (_entry("@alice", 0.9),),
            "orphan/lost.py": (),
        }
    )
    content = _build_codeowners_content(ownership, config)
    assert "# Unowned paths (needs triage)" in content
    assert "# /orphan/lost.py" in content


def test_collect_unowned_paths() -> None:
    ownership = _make_ownership({"a.py": (), "b.py": (_entry("@x", 0.9),)})
    assert _collect_unowned_paths(ownership) == ["/a.py"]


def test_team_resolution_collapses_owner_set(tmp_path: Path) -> None:
    config = Config(
        analysis=AnalysisConfig(confidence_threshold=0.0),
        github=GithubConfig(org="acme", resolve_teams=True),
    )
    ownership = _make_ownership(
        {"src/main.py": (_entry("@alice", 0.9), _entry("@bob", 0.8))},
    )
    with patch(
        "checkowners.github.create_team_resolver",
        return_value=lambda owners: "@acme/backend",
    ):
        content = _build_codeowners_content(ownership, config, token="t", org="acme")
    assert "/src/main.py @acme/backend" in content


def test_output_ends_with_newline() -> None:
    ownership = _make_ownership({"src/main.py": (_entry("@alice", 0.9),)})
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert content.endswith("\n")


def test_bracket_segments_become_wildcards() -> None:
    """Next.js dynamic routes ([id]) are invalid CODEOWNERS ranges."""
    ownership = _make_ownership(
        {
            "app/[teamId]/page.tsx": (_entry("@alice", 0.9),),
            "app/[teamId]/layout.tsx": (_entry("@alice", 0.8),),
            "app/other.tsx": (_entry("@bob", 0.9),),
        }
    )
    content = _build_codeowners_content(ownership, _zero_threshold())
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/app/*/ @alice", "/app/other.tsx @bob"]
    assert "[" not in content


def test_colliding_sanitized_patterns_merge_owners() -> None:
    ownership = _make_ownership(
        {
            "app/[teamId]/page.tsx": (_entry("@alice", 0.9),),
            "app/[userId]/view.tsx": (_entry("@bob", 0.6),),
        }
    )
    config = _zero_threshold(consolidate=False)
    content = _build_codeowners_content(ownership, config)
    lines = [line for line in content.splitlines() if line and not line.startswith("#")]
    assert lines == ["/app/*/page.tsx @alice", "/app/*/view.tsx @bob"]


def test_pattern_spaces_escaped_on_write() -> None:
    ownership = _make_ownership({"docs/getting started.md": (_entry("@alice", 0.9),)})
    content = _build_codeowners_content(ownership, _zero_threshold())
    assert "/docs/getting\\ started.md @alice" in content


@pytest.fixture(autouse=True)
def _mock_tracked_paths() -> None:
    with patch("checkowners.generate._tracked_paths", return_value=()):
        yield


def test_verifier_catches_later_broad_rule() -> None:
    ownership = _make_ownership({"src/a.py": (_entry("@alice", 0.9),)})
    with pytest.raises(CodeownersGenerationError, match=r"src/a.py.*alice.*bob.*line 2"):
        verify_round_trip("/src/a.py @alice\n* @bob\n", ownership, _zero_threshold(), ["src/a.py"])


def test_consolidation_does_not_claim_unowned_tracked_files(tmp_path: Path) -> None:
    ownership = _make_ownership(
        {
            "src/a.py": (_entry("@alice", 0.9),),
            "src/b.py": (_entry("@alice", 0.9),),
        }
    )
    with patch(
        "checkowners.generate._tracked_paths", return_value=("src/a.py", "src/b.py", "src/c.py")
    ):
        content = generate_codeowners(tmp_path, ownership, _zero_threshold())
    assert "/src/ @alice" not in content
    assert "/src/a.py @alice" in content


def test_failed_verification_preserves_existing_file(tmp_path: Path) -> None:
    config = _zero_threshold()
    target = tmp_path / "CODEOWNERS"
    before = config.output.header + "\n* @human\n"
    target.write_text(before)
    ownership = _make_ownership({"src/a.py": (_entry("@alice", 0.9),)})
    with (
        patch("checkowners.generate._build_codeowners_content", return_value="* @wrong\n"),
        pytest.raises(CodeownersGenerationError),
    ):
        generate_codeowners(tmp_path, ownership, config, codeowners_path=target, force=True)
    assert target.read_text() == before


def test_size_limit_counts_utf8_bytes_and_force_overrides(tmp_path: Path) -> None:
    ownership = _make_ownership({"café.py": (_entry("@alice", 0.9),)})
    config = _zero_threshold()
    content = _build_codeowners_content(ownership, config)
    config = replace(config, output=replace(config.output, max_bytes=len(content)))
    with pytest.raises(CodeownersGenerationError, match="output.max_bytes"):
        generate_codeowners(tmp_path, ownership, config)
    assert not (tmp_path / ".github" / "CODEOWNERS").exists()
    assert generate_codeowners(tmp_path, ownership, config, force=True) == content


def test_warns_at_two_megabytes(tmp_path: Path) -> None:
    config = _zero_threshold()
    with (
        patch("checkowners.generate._build_codeowners_content", return_value="#" + "x" * 1_999_999),
        pytest.warns(UserWarning, match="2000000 bytes"),
    ):
        generate_codeowners(tmp_path, _make_ownership({}), config)


def test_verification_can_be_disabled_explicitly(tmp_path: Path) -> None:
    config = _zero_threshold()
    config = replace(config, output=replace(config.output, verify_round_trip=False))
    with patch("checkowners.generate.verify_round_trip") as verify:
        generate_codeowners(tmp_path, _make_ownership({}), config)
    verify.assert_not_called()


def test_verifies_resolved_teams(tmp_path: Path) -> None:
    config = _zero_threshold()
    ownership = _make_ownership({"src/a.py": (_entry("@alice", 0.9), _entry("@bob", 0.8))})
    with patch("checkowners.github.create_team_resolver", return_value=lambda owners: "@acme/team"):
        content = generate_codeowners(tmp_path, ownership, config, token="test", org="acme")
    assert "@acme/team" in content


def test_verifier_reports_no_matching_rule() -> None:
    ownership = _make_ownership({"a.py": (_entry("@alice", 0.9),)})
    with pytest.raises(CodeownersGenerationError, match="no matching rule"):
        verify_round_trip("", ownership, _zero_threshold(), ["a.py"])


def test_verifier_compares_owner_sets_case_insensitively() -> None:
    ownership = _make_ownership({"a.py": (_entry("@Alice", 0.9), _entry("@Bob", 0.8))})
    verify_round_trip("/a.py @bob @alice\n", ownership, _zero_threshold(), ["a.py"])


def test_tracked_paths_are_nul_separated(tmp_path: Path) -> None:
    with patch(
        "checkowners.generate.subprocess.run", return_value=MagicMock(stdout=b"a b\0c\nd\0")
    ) as run:
        assert _tracked_paths(tmp_path) == ("a b", "c\nd")
    assert run.call_args.args[0] == ["git", "ls-files", "-z"]


def test_tracked_paths_fail_closed(tmp_path: Path) -> None:
    with (
        patch(
            "checkowners.generate.subprocess.run",
            side_effect=subprocess.CalledProcessError(1, "git"),
        ),
        pytest.raises(CodeownersGenerationError, match="Cannot list tracked"),
    ):
        _tracked_paths(tmp_path)


@pytest.mark.parametrize("consolidate", [True, False])
def test_generated_rules_round_trip_across_owner_combinations(consolidate: bool) -> None:
    from itertools import product

    for assignment in product(((), (_entry("@alice", 0.9),), (_entry("@bob", 0.8),)), repeat=4):
        ownership = _make_ownership(
            dict(zip(("src/a.py", "src/b.py", "docs/a.md", "docs/b.md"), assignment, strict=True))
        )
        config = _zero_threshold(consolidate=consolidate)
        content = _build_codeowners_content(ownership, config, tracked_paths=ownership.paths)
        verify_round_trip(content, ownership, config, ownership.paths)
