"""CODEOWNERS file generator from confidence-scored ownership.

Per-file inference is consolidated to directory-level rules before writing:
when every inferred file under a directory shares the same owner set, one
``/dir/ @owners`` line replaces the per-file lines. This keeps the file
readable and, more importantly, makes brand-new files under that directory
match a rule, which per-file patterns never would. Disable via
``output.consolidate: false``.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from checkowners.github import create_team_resolver
from checkowners.models import Config, OwnerEntry, OwnershipMap
from checkowners.patterns import match_path, parse_rules

_DEFAULT_CODEOWNERS_PATH = ".github/CODEOWNERS"
SIZE_WARN_BYTES = 2 * 1024 * 1024

_OwnerKey = frozenset[str]
_FileRow = tuple[str, tuple[OwnerEntry, ...]]
_ExpectedOwners = dict[str, frozenset[str]]


class CodeownersGenerateError(Exception):
    """Base for generate failures that should exit without writing."""


class CodeownersOverwriteError(CodeownersGenerateError):
    """Raised when the target CODEOWNERS was not generated by checkOwners."""


class CodeownersVerificationError(CodeownersGenerateError):
    """Raised when generated rules do not resolve to the intended owners."""


class CodeownersSizeError(CodeownersGenerateError):
    """Raised when generated content exceeds output.max_bytes without force."""


@dataclass(frozen=True)
class _Row:
    pattern: str
    owners: tuple[OwnerEntry, ...]
    paths: tuple[str, ...] = ()


def generate_codeowners(
    repo_root: Path,
    ownership: OwnershipMap,
    config: Config,
    *,
    codeowners_path: Path | None = None,
    token: str = "",
    org: str = "",
    force: bool = False,
) -> str:
    """Generate CODEOWNERS file content and write it to disk.

    Refuses to overwrite a hand-written CODEOWNERS (one that lacks the
    machine-generated header) unless ``force`` is set. ``force`` also writes
    past ``output.max_bytes``. Round-trip verification is not skipped.
    """
    content, expected = _render_codeowners(ownership, config, token=token, org=org)
    if config.output.verify_round_trip:
        verify_round_trip(content, expected)
    _ensure_size_ok(content, config.output.max_bytes, force=force)
    target = codeowners_path or (repo_root / _DEFAULT_CODEOWNERS_PATH)
    ensure_overwrite_safe(target, config.output.header, force=force)
    _write_codeowners(target, content)
    return content


def ensure_overwrite_safe(target: Path, header: str, *, force: bool) -> None:
    if force or not target.exists():
        return
    existing = target.read_text(encoding="utf-8")
    if header and header in existing:
        return
    msg = (
        f"{target} exists but was not generated by checkOwners "
        "(machine-generated header not found). Re-run with --force to overwrite it."
    )
    raise CodeownersOverwriteError(msg)


def codeowners_write_metrics(content: str) -> dict[str, int]:
    return {
        "bytes_written": len(content.encode("utf-8")),
        "rules_written": len(parse_rules(content)),
    }


def verify_round_trip(content: str, expected: _ExpectedOwners) -> None:
    """Fail if any assigned path resolves to owners other than ``expected``.

    ``expected`` maps repo-relative paths to the owner set generation assigned
    after consolidation, sanitization, merge, and team collapse.
    """
    rules = parse_rules(content)
    raw_lines = content.splitlines()
    for path, intended in expected.items():
        rule = match_path(rules, path)
        resolved = frozenset(owner.casefold() for owner in rule.owners) if rule else frozenset()
        if resolved == intended:
            continue
        winning = raw_lines[rule.line_number - 1] if rule is not None else "(none)"
        intended_s = " ".join(sorted(intended)) or "(none)"
        resolved_s = " ".join(sorted(resolved)) or "(none)"
        msg = (
            f"Round-trip verification failed for {path}: "
            f"intended {intended_s}, resolved {resolved_s}, "
            f"winning rule: {winning}"
        )
        raise CodeownersVerificationError(msg)


def _ensure_size_ok(content: str, max_bytes: int, *, force: bool) -> None:
    size = len(content.encode("utf-8"))
    if size <= max_bytes or force:
        return
    msg = (
        f"Generated CODEOWNERS is {size} bytes, which exceeds "
        f"output.max_bytes ({max_bytes}). GitHub does not load CODEOWNERS "
        f"files over 3 MB. Re-run with --force to write it anyway."
    )
    raise CodeownersSizeError(msg)


def _build_codeowners_content(
    ownership: OwnershipMap,
    config: Config,
    *,
    token: str = "",
    org: str = "",
) -> str:
    content, _expected = _render_codeowners(ownership, config, token=token, org=org)
    return content


def _render_codeowners(
    ownership: OwnershipMap,
    config: Config,
    *,
    token: str = "",
    org: str = "",
) -> tuple[str, _ExpectedOwners]:
    lines: list[str] = [config.output.header, ""]
    rows = _collect_rows(ownership, config)
    unowned_paths = _collect_unowned_paths(ownership)
    expected: _ExpectedOwners = {}

    team_resolve: Callable[[tuple[str, ...]], str | None] | None = None
    if config.github.resolve_teams and token and org:
        team_resolve = create_team_resolver(token, org)

    for row in rows:
        written_handles = tuple(o.handle for o in row.owners)
        if team_resolve is not None:
            team = team_resolve(written_handles)
            if team is not None:
                written_handles = (team,)
        written = frozenset(handle.casefold() for handle in written_handles)
        for path in row.paths:
            expected[path] = written
        lines.append(_format_line(row.pattern, written_handles, row.owners, config))

    if rows and config.output.include_confidence:
        lines.append("")
        lines.append("# Confidence scores reflect each owner's expertise as of")
        lines.append(f"# {ownership.last_analyzed.isoformat(timespec='seconds')}.")

    if config.output.include_unowned and unowned_paths:
        lines.append("")
        lines.append("# Unowned paths (needs triage)")
        for path in unowned_paths:
            lines.append(f"# {path}")

    lines.append("")
    return "\n".join(lines), expected


def _format_line(
    pattern: str,
    written_handles: tuple[str, ...],
    owners: tuple[OwnerEntry, ...],
    config: Config,
) -> str:
    escaped_pattern = pattern.replace(" ", "\\ ")
    line = f"{escaped_pattern} {' '.join(written_handles)}"
    if not config.output.include_confidence:
        return line
    annotations = " ".join(f"{o.handle}({o.score_label})" for o in owners)
    return f"{line}  # {annotations}"


def _collect_rows(ownership: OwnershipMap, config: Config) -> list[_Row]:
    """Confidence-filtered rows, consolidated to directories when uniform."""
    filtered: list[_FileRow] = []
    for path, path_ownership in sorted(ownership.paths.items()):
        owners = tuple(
            o for o in path_ownership.owners if o.confidence >= config.analysis.confidence_threshold
        )
        if owners:
            filtered.append((path.lstrip("/"), owners))
    filtered.sort(key=lambda row: row[0])
    if config.output.consolidate:
        rows = _consolidate(filtered)
    else:
        rows = [_Row(pattern=f"/{path}", owners=owners, paths=(path,)) for path, owners in filtered]
    rows = _merge_same_pattern(
        _Row(pattern=_sanitize_pattern(row.pattern), owners=row.owners, paths=row.paths)
        for row in rows
    )
    rows.sort(key=lambda row: row.pattern)
    return rows


def _sanitize_pattern(pattern: str) -> str:
    """Make a literal path emittable as a valid GitHub CODEOWNERS pattern.

    GitHub rejects ``[...]`` as an unsupported character range and ignores the
    whole line, silently un-owning the path. Bracket-bearing segments (Next.js
    dynamic routes like ``[companyId]``) become ``*``, the closest valid
    single-segment wildcard.
    """
    if "[" not in pattern and "]" not in pattern:
        return pattern
    segments = [
        "*" if ("[" in segment or "]" in segment) else segment for segment in pattern.split("/")
    ]
    return "/".join(segments)


def _merge_same_pattern(rows: Iterable[_Row]) -> list[_Row]:
    """Merge rows whose sanitized patterns collide, unioning their owners."""
    grouped: dict[str, list[_Row]] = {}
    for row in rows:
        grouped.setdefault(row.pattern, []).append(row)
    merged: list[_Row] = []
    for pattern, bucket in grouped.items():
        if len(bucket) == 1:
            merged.append(bucket[0])
        else:
            assigned: list[str] = []
            for row in bucket:
                assigned.extend(row.paths)
            merged.append(
                _Row(
                    pattern=pattern,
                    owners=_merge_owners([row.owners for row in bucket]),
                    paths=tuple(assigned),
                )
            )
    return merged


def _owner_key(owners: tuple[OwnerEntry, ...]) -> _OwnerKey:
    return frozenset(o.handle.casefold() for o in owners)


def _ancestors(path: str) -> list[str]:
    """Directory prefixes of a file path, shortest first ('' is the repo root)."""
    segments = path.split("/")
    return ["/".join(segments[:i]) for i in range(len(segments))]


def _consolidate(files: list[_FileRow]) -> list[_Row]:
    """Merge per-file rows into directory rows where owner sets are uniform.

    Every file is attached to its shortest ancestor directory whose inferred
    files all share one owner set (so the broadest safe rule wins); files with
    no such ancestor keep their own per-file line.
    """
    dir_keys: dict[str, set[_OwnerKey]] = {}
    dir_files: dict[str, list[_FileRow]] = {}
    for path, owners in files:
        key = _owner_key(owners)
        for ancestor in _ancestors(path):
            dir_keys.setdefault(ancestor, set()).add(key)
            dir_files.setdefault(ancestor, []).append((path, owners))

    def is_uniform(directory: str) -> bool:
        if len(dir_keys[directory]) != 1 or len(dir_files[directory]) < 2:
            return False
        if directory == "":
            # A root catch-all (*) claims every future file in the repo;
            # only justified when the evidence spans several top-level entries.
            top_level = {path.split("/", 1)[0] for path, _ in dir_files[directory]}
            return len(top_level) > 1
        return True

    rows: list[_Row] = []
    emitted_dirs: set[str] = set()
    for path, owners in files:
        chosen = next((d for d in _ancestors(path) if is_uniform(d)), None)
        if chosen is None:
            rows.append(_Row(pattern=f"/{path}", owners=owners, paths=(path,)))
        elif chosen not in emitted_dirs:
            emitted_dirs.add(chosen)
            merged = _merge_owners([o for _, o in dir_files[chosen]])
            pattern = "*" if chosen == "" else f"/{chosen}/"
            assigned = tuple(p for p, _ in dir_files[chosen])
            rows.append(_Row(pattern=pattern, owners=merged, paths=assigned))
    return rows


def _merge_owners(owner_lists: list[tuple[OwnerEntry, ...]]) -> tuple[OwnerEntry, ...]:
    """Aggregate per-file entries of the same owners into one ranked tuple."""
    by_handle: dict[str, list[OwnerEntry]] = {}
    for owners in owner_lists:
        for owner in owners:
            by_handle.setdefault(owner.handle, []).append(owner)
    merged: list[OwnerEntry] = []
    for handle, entries in by_handle.items():
        scores = [e.ownership_score for e in entries]
        qualities = [e.evidence_quality for e in entries]
        last_commits = [e.last_commit for e in entries if e.last_commit is not None]
        latest: datetime | None = max(last_commits) if last_commits else None
        merged.append(
            OwnerEntry(
                handle=handle,
                ownership_score=sum(scores) / len(scores),
                last_commit=latest,
                commits=sum(e.commits for e in entries),
                evidence_quality=sum(qualities) / len(qualities),
                score_breakdown=None,
            )
        )
    merged.sort(key=lambda e: (-e.confidence, e.handle))
    return tuple(merged)


def _collect_unowned_paths(ownership: OwnershipMap) -> list[str]:
    """Paths present in the map with no inferred owners."""
    return sorted(f"/{path.lstrip('/')}" for path, po in ownership.paths.items() if not po.owners)


def _write_codeowners(codeowners_path: Path, content: str) -> None:
    codeowners_path.parent.mkdir(parents=True, exist_ok=True)
    codeowners_path.write_text(content, encoding="utf-8")
