"""CODEOWNERS file generator from confidence-scored ownership.

Per-file inference is consolidated to directory-level rules before writing:
when every inferred file under a directory shares the same owner set, one
``/dir/ @owners`` line replaces the per-file lines. This keeps the file
readable and, more importantly, makes brand-new files under that directory
match a rule, which per-file patterns never would. Disable via
``output.consolidate: false``.
"""

from __future__ import annotations

import subprocess
import warnings
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from checkowners.models import Config, OwnerEntry, OwnershipMap
from checkowners.patterns import match_path, parse_rules

_DEFAULT_CODEOWNERS_PATH = ".github/CODEOWNERS"

_OwnerKey = frozenset[str]
_FileRow = tuple[str, tuple[OwnerEntry, ...]]
_TeamResolver = Callable[[tuple[str, ...]], str | None]
_SIZE_WARNING_BYTES = 2_000_000


class CodeownersGenerationError(ValueError):
    """Generated rules cannot safely represent the intended ownership."""


class CodeownersOverwriteError(Exception):
    """Raised when the target CODEOWNERS was not generated by checkOwners."""


@dataclass(frozen=True)
class _Row:
    """One output line: a CODEOWNERS pattern plus its ranked owners."""

    pattern: str
    owners: tuple[OwnerEntry, ...]


def generate_codeowners(
    repo_root: Path,
    ownership: OwnershipMap,
    config: Config,
    *,
    codeowners_path: Path | None = None,
    token: str = "",
    org: str = "",
    force: bool = False,
) -> str:
    """Generate CODEOWNERS file content and write it to disk.

    Refuses to overwrite a hand-written CODEOWNERS (one that lacks the
    machine-generated header) unless ``force`` is set, so a curated file is
    never silently destroyed.
    """
    target = codeowners_path or (repo_root / _DEFAULT_CODEOWNERS_PATH)
    ensure_overwrite_safe(target, config.output.header, force=force)
    tracked = _tracked_paths(repo_root) if config.output.verify_round_trip else ()
    resolver = _team_resolver(config, token, org)
    content = _build_codeowners_content(
        ownership, config, tracked_paths=tracked, team_resolve=resolver
    )
    size = len(content.encode("utf-8"))
    if config.output.max_bytes <= 0:
        raise CodeownersGenerationError("output.max_bytes must be a positive integer")
    if size > config.output.max_bytes and not force:
        raise CodeownersGenerationError(
            f"Generated CODEOWNERS is {size} bytes, exceeding output.max_bytes "
            f"({config.output.max_bytes}). Reduce the rules or use --force "
            "to override the size limit."
        )
    if size >= _SIZE_WARNING_BYTES:
        warnings.warn(
            f"Generated CODEOWNERS is {size} bytes; GitHub ignores files over 3 MB.",
            UserWarning,
            stacklevel=2,
        )
    if config.output.verify_round_trip:
        verify_round_trip(content, ownership, config, tracked, team_resolve=resolver)
    _write_codeowners(target, content)
    return content


def _tracked_paths(repo_root: Path) -> tuple[str, ...]:
    try:
        result = subprocess.run(
            ["git", "ls-files", "-z"], cwd=repo_root, capture_output=True, check=True
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise CodeownersGenerationError(
            "Cannot list tracked files for CODEOWNERS verification"
        ) from exc
    return tuple(sorted(set(result.stdout.decode("utf-8").rstrip("\0").split("\0")) - {""}))


def _team_resolver(config: Config, token: str, org: str) -> _TeamResolver | None:
    if config.github.resolve_teams and token and org:
        from checkowners.github import create_team_resolver

        return create_team_resolver(token, org)
    return None


def verify_round_trip(
    content: str,
    ownership: OwnershipMap,
    config: Config,
    tracked_paths: Iterable[str],
    *,
    team_resolve: _TeamResolver | None = None,
) -> None:
    """Check the candidate before writing, including tracked paths with no owners."""
    rules = parse_rules(content)
    expected = {
        path.lstrip("/"): tuple(
            owner.handle
            for owner in po.owners
            if owner.confidence >= config.analysis.confidence_threshold
        )
        for path, po in ownership.paths.items()
    }
    for path in sorted(set(tracked_paths) | expected.keys()):
        intended = expected.get(path, ())
        if intended and team_resolve is not None:
            team = team_resolve(intended)
            if team is not None:
                intended = (team,)
        winner = match_path(rules, path)
        resolved = winner.owners if winner else ()
        if {owner.casefold() for owner in intended} != {owner.casefold() for owner in resolved}:
            rule = (
                f"line {winner.line_number} ({winner.pattern!r})" if winner else "no matching rule"
            )
            raise CodeownersGenerationError(
                f"CODEOWNERS verification failed for {path!r}: intended {list(intended)!r}, "
                f"resolved {list(resolved)!r}; winning rule: {rule}."
            )


def ensure_overwrite_safe(target: Path, header: str, *, force: bool) -> None:
    if force or not target.exists():
        return
    existing = target.read_text(encoding="utf-8")
    if header and header in existing:
        return
    msg = (
        f"{target} exists but was not generated by checkOwners "
        "(machine-generated header not found). Re-run with --force to overwrite it."
    )
    raise CodeownersOverwriteError(msg)


def _build_codeowners_content(
    ownership: OwnershipMap,
    config: Config,
    *,
    token: str = "",
    org: str = "",
    tracked_paths: Iterable[str] = (),
    team_resolve: _TeamResolver | None = None,
) -> str:
    """Build the CODEOWNERS file content string."""
    lines: list[str] = [config.output.header, ""]
    rows = _collect_rows(ownership, config, tracked_paths=tracked_paths)
    unowned_paths = _collect_unowned_paths(ownership)

    if team_resolve is None:
        team_resolve = _team_resolver(config, token, org)

    for row in rows:
        handles = tuple(o.handle for o in row.owners)
        if team_resolve is not None:
            team = team_resolve(handles)
            if team is not None:
                lines.append(_format_line(row.pattern, (team,), row.owners, config))
                continue
        lines.append(_format_line(row.pattern, handles, row.owners, config))

    if rows and config.output.include_confidence:
        lines.append("")
        lines.append("# Confidence scores reflect each owner's expertise as of")
        lines.append(f"# {ownership.last_analyzed.isoformat(timespec='seconds')}.")

    if config.output.include_unowned and unowned_paths:
        lines.append("")
        lines.append("# Unowned paths (needs triage)")
        for path in unowned_paths:
            lines.append(f"# {path}")

    lines.append("")
    return "\n".join(lines)


def _format_line(
    pattern: str,
    written_handles: tuple[str, ...],
    owners: tuple[OwnerEntry, ...],
    config: Config,
) -> str:
    escaped_pattern = pattern.replace(" ", "\\ ")
    line = f"{escaped_pattern} {' '.join(written_handles)}"
    if not config.output.include_confidence:
        return line
    annotations = " ".join(f"{o.handle}({o.confidence:.2f})" for o in owners)
    return f"{line}  # {annotations}"


def _collect_rows(
    ownership: OwnershipMap, config: Config, *, tracked_paths: Iterable[str] = ()
) -> list[_Row]:
    """Confidence-filtered rows, consolidated to directories when uniform."""
    filtered: list[_FileRow] = []
    for path, path_ownership in ownership.paths.items():
        owners = tuple(
            o for o in path_ownership.owners if o.confidence >= config.analysis.confidence_threshold
        )
        if owners:
            filtered.append((path.lstrip("/"), owners))
    if config.output.consolidate:
        owned = {path for path, _ in filtered}
        unowned = (set(tracked_paths) | {p.lstrip("/") for p in ownership.paths}) - owned
        rows = _consolidate(filtered, unowned_paths=unowned)
    else:
        rows = [_Row(pattern=f"/{path}", owners=owners) for path, owners in filtered]
    rows = _merge_same_pattern(
        _Row(pattern=_sanitize_pattern(row.pattern), owners=row.owners) for row in rows
    )
    rows.sort(key=lambda row: row.pattern)
    return rows


def _sanitize_pattern(pattern: str) -> str:
    """Make a literal path emittable as a valid GitHub CODEOWNERS pattern.

    GitHub rejects ``[...]`` as an unsupported character range and ignores the
    whole line, silently un-owning the path. Bracket-bearing segments (Next.js
    dynamic routes like ``[companyId]``) become ``*``, the closest valid
    single-segment wildcard.
    """
    if "[" not in pattern and "]" not in pattern:
        return pattern
    segments = [
        "*" if ("[" in segment or "]" in segment) else segment for segment in pattern.split("/")
    ]
    return "/".join(segments)


def _merge_same_pattern(rows: Iterable[_Row]) -> list[_Row]:
    """Merge rows whose sanitized patterns collide, unioning their owners."""
    grouped: dict[str, list[_Row]] = {}
    for row in rows:
        grouped.setdefault(row.pattern, []).append(row)
    merged: list[_Row] = []
    for pattern, bucket in grouped.items():
        if len(bucket) == 1:
            merged.append(bucket[0])
        else:
            merged.append(
                _Row(pattern=pattern, owners=_merge_owners([row.owners for row in bucket]))
            )
    return merged


def _owner_key(owners: tuple[OwnerEntry, ...]) -> _OwnerKey:
    return frozenset(o.handle.casefold() for o in owners)


def _ancestors(path: str) -> list[str]:
    """Directory prefixes of a file path, shortest first ('' is the repo root)."""
    segments = path.split("/")
    return ["/".join(segments[:i]) for i in range(len(segments))]


def _consolidate(files: list[_FileRow], *, unowned_paths: Iterable[str] = ()) -> list[_Row]:
    """Merge per-file rows into directory rows where owner sets are uniform.

    Every file is attached to its shortest ancestor directory whose inferred
    files all share one owner set (so the broadest safe rule wins); files with
    no such ancestor keep their own per-file line.
    """
    dir_keys: dict[str, set[_OwnerKey]] = {}
    dir_files: dict[str, list[_FileRow]] = {}
    for path, owners in files:
        key = _owner_key(owners)
        for ancestor in _ancestors(path):
            dir_keys.setdefault(ancestor, set()).add(key)
            dir_files.setdefault(ancestor, []).append((path, owners))

    blocked_dirs = {ancestor for path in unowned_paths for ancestor in _ancestors(path)}

    def is_uniform(directory: str) -> bool:
        if directory in blocked_dirs:
            return False
        if len(dir_keys[directory]) != 1 or len(dir_files[directory]) < 2:
            return False
        if directory == "":
            # A root catch-all (*) claims every future file in the repo;
            # only justified when the evidence spans several top-level entries.
            top_level = {path.split("/", 1)[0] for path, _ in dir_files[directory]}
            return len(top_level) > 1
        return True

    rows: list[_Row] = []
    emitted_dirs: set[str] = set()
    for path, owners in files:
        chosen = next((d for d in _ancestors(path) if is_uniform(d)), None)
        if chosen is None:
            rows.append(_Row(pattern=f"/{path}", owners=owners))
        elif chosen not in emitted_dirs:
            emitted_dirs.add(chosen)
            merged = _merge_owners([o for _, o in dir_files[chosen]])
            pattern = "*" if chosen == "" else f"/{chosen}/"
            rows.append(_Row(pattern=pattern, owners=merged))
    return rows


def _merge_owners(owner_lists: list[tuple[OwnerEntry, ...]]) -> tuple[OwnerEntry, ...]:
    """Aggregate per-file entries of the same owners into one ranked tuple."""
    by_handle: dict[str, list[OwnerEntry]] = {}
    for owners in owner_lists:
        for owner in owners:
            by_handle.setdefault(owner.handle, []).append(owner)
    merged: list[OwnerEntry] = []
    for handle, entries in by_handle.items():
        confidences = [e.confidence for e in entries]
        last_commits = [e.last_commit for e in entries if e.last_commit is not None]
        latest: datetime | None = max(last_commits) if last_commits else None
        merged.append(
            OwnerEntry(
                handle=handle,
                confidence=sum(confidences) / len(confidences),
                last_commit=latest,
                commits=sum(e.commits for e in entries),
                score_breakdown=None,
            )
        )
    merged.sort(key=lambda e: (-e.confidence, e.handle))
    return tuple(merged)


def _collect_unowned_paths(ownership: OwnershipMap) -> list[str]:
    """Paths present in the map with no inferred owners."""
    return sorted(f"/{path.lstrip('/')}" for path, po in ownership.paths.items() if not po.owners)


def _write_codeowners(codeowners_path: Path, content: str) -> None:
    codeowners_path.parent.mkdir(parents=True, exist_ok=True)
    codeowners_path.write_text(content, encoding="utf-8")
