"""Data models for checkOwners. Only dataclasses; no other classes."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal

Severity = Literal["low", "medium", "high", "critical"]
DriftMode = Literal["commit", "repo", "both"]


@dataclass(frozen=True)
class AnalysisConfig:
    lookback_days: int = 365
    min_commits: int = 3
    top_n_owners: int = 3
    confidence_threshold: float = 0.3
    exclude_bots: bool = True


@dataclass(frozen=True)
class ScoringConfig:
    recency_half_life_days: int = 90
    recency_weight: float = 0.35
    frequency_weight: float = 0.25
    blame_weight: float = 0.25
    review_weight: float = 0.15


@dataclass(frozen=True)
class DecayConfig:
    threshold_days: int = 180
    alert_on_decay: bool = True


@dataclass(frozen=True)
class BusFactorConfig:
    critical_threshold: int = 1
    warn_threshold: int = 2


@dataclass(frozen=True)
class PathsConfig:
    #: CODEOWNERS itself is excluded: sync commits would otherwise make
    #: whoever runs the tool the inferred "owner" of the generated file,
    #: perturbing every subsequent run.
    exclude: tuple[str, ...] = (
        "*.lock",
        "package-lock.json",
        "pnpm-lock.yaml",
        "dist/**",
        "vendor/**",
        "node_modules/**",
        "*.generated.*",
        "*.min.js",
        "*.min.css",
        "*.map",
        "*.whl",
        ".github/CODEOWNERS",
        "CODEOWNERS",
        "docs/CODEOWNERS",
    )


@dataclass(frozen=True)
class OutputConfig:
    header: str = "# Generated by checkOwners. Do not edit manually."
    include_unowned: bool = False
    include_confidence: bool = False
    consolidate: bool = True


@dataclass(frozen=True)
class DriftConfig:
    mode: DriftMode = "commit"
    min_confidence_delta: float = 0.2


@dataclass(frozen=True)
class NotificationsConfig:
    webhook_url: str = ""
    include_unchanged: bool = False
    severity_threshold: Severity = "medium"


@dataclass(frozen=True)
class GithubConfig:
    org: str = ""
    resolve_handles: bool = True
    resolve_teams: bool = True
    api_enabled: bool = False


@dataclass(frozen=True)
class Config:
    analysis: AnalysisConfig = field(default_factory=AnalysisConfig)
    scoring: ScoringConfig = field(default_factory=ScoringConfig)
    decay: DecayConfig = field(default_factory=DecayConfig)
    bus_factor: BusFactorConfig = field(default_factory=BusFactorConfig)
    paths: PathsConfig = field(default_factory=PathsConfig)
    output: OutputConfig = field(default_factory=OutputConfig)
    drift: DriftConfig = field(default_factory=DriftConfig)
    notifications: NotificationsConfig = field(default_factory=NotificationsConfig)
    github: GithubConfig = field(default_factory=GithubConfig)


@dataclass(frozen=True)
class ConfidenceScore:
    """Breakdown of a single owner's confidence score for a path."""

    total: float
    recency: float
    frequency: float
    blame: float
    review: float


@dataclass(frozen=True)
class OwnerEntry:
    """A single owner of a path with confidence and provenance."""

    handle: str
    confidence: float
    last_commit: datetime | None
    commits: int
    score_breakdown: ConfidenceScore | None = None


@dataclass(frozen=True)
class DecayWarning:
    handle: str
    path: str
    last_commit: datetime
    days_since_last_commit: int
    historical_confidence: float


@dataclass(frozen=True)
class PathOwnership:
    """All information known about a single path's ownership."""

    owners: tuple[OwnerEntry, ...]
    bus_factor: int
    decay_warnings: tuple[DecayWarning, ...] = ()


@dataclass(frozen=True)
class OwnershipMap:
    """Confidence-scored ownership across all paths."""

    paths: dict[str, PathOwnership]
    last_analyzed: datetime


@dataclass(frozen=True)
class ExpertiseRank:
    """Per-path ranking entry for the expertise command."""

    handle: str
    confidence: float
    commits: int
    last_commit: datetime | None


@dataclass(frozen=True)
class TeamCluster:
    """Inferred team boundary from commit co-occurrence."""

    name: str
    members: tuple[str, ...]
    primary_paths: tuple[str, ...]
    declared: bool = False


@dataclass(frozen=True)
class BusFactor:
    path: str
    bus_factor: int
    contributors_above_threshold: tuple[str, ...]
    recommended_backups: tuple[str, ...]


@dataclass(frozen=True)
class DriftEntry:
    path: str
    confidence_delta: float
    reason: str = ""
    bus_factor: int | None = None
    decay: bool = False


@dataclass(frozen=True)
class DriftResult:
    stale: tuple[DriftEntry, ...]
    missing: tuple[DriftEntry, ...]
    changed: tuple[DriftEntry, ...]
    drift_detected: bool
    #: Human-readable caveats about the comparison (e.g. inferred owners are
    #: raw emails while CODEOWNERS uses @handles, making owner-set comparison
    #: impossible without handle resolution).
    notes: tuple[str, ...] = ()

    @property
    def max_confidence_delta(self) -> float:
        entries = (*self.stale, *self.missing, *self.changed)
        if not entries:
            return 0.0
        return max(abs(e.confidence_delta) for e in entries)
